/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as ForHotelsRouteImport } from './routes/for-hotels'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as HotelsIdRouteImport } from './routes/hotels.$id'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardInvitationsRouteImport } from './routes/_authenticated/dashboard.invitations'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardRfqsIndexRouteImport } from './routes/_authenticated/dashboard.rfqs.index'
import { Route as AuthenticatedDashboardHotelIndexRouteImport } from './routes/_authenticated/dashboard.hotel.index'
import { Route as AuthenticatedDashboardRfqsNewRouteImport } from './routes/_authenticated/dashboard.rfqs.new'
import { Route as AuthenticatedDashboardRfqsIdRouteImport } from './routes/_authenticated/dashboard.rfqs.$id'
import { Route as AuthenticatedDashboardHotelIdRouteImport } from './routes/_authenticated/dashboard.hotel.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHotelsRoute = ForHotelsRouteImport.update({
  id: '/for-hotels',
  path: '/for-hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RequestsRoute,
} as any)
const HotelsIdRoute = HotelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HotelsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInvitationsRoute =
  AuthenticatedDashboardInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRfqsIndexRoute =
  AuthenticatedDashboardRfqsIndexRouteImport.update({
    id: '/rfqs/',
    path: '/rfqs/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHotelIndexRoute =
  AuthenticatedDashboardHotelIndexRouteImport.update({
    id: '/hotel/',
    path: '/hotel/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRfqsNewRoute =
  AuthenticatedDashboardRfqsNewRouteImport.update({
    id: '/rfqs/new',
    path: '/rfqs/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRfqsIdRoute =
  AuthenticatedDashboardRfqsIdRouteImport.update({
    id: '/rfqs/$id',
    path: '/rfqs/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHotelIdRoute =
  AuthenticatedDashboardHotelIdRouteImport.update({
    id: '/hotel/$id',
    path: '/hotel/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-hotels': typeof ForHotelsRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/request-quote': typeof RequestQuoteRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/hotels/$id': typeof HotelsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/invitations': typeof AuthenticatedDashboardInvitationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/hotel/$id': typeof AuthenticatedDashboardHotelIdRoute
  '/dashboard/rfqs/$id': typeof AuthenticatedDashboardRfqsIdRoute
  '/dashboard/rfqs/new': typeof AuthenticatedDashboardRfqsNewRoute
  '/dashboard/hotel/': typeof AuthenticatedDashboardHotelIndexRoute
  '/dashboard/rfqs/': typeof AuthenticatedDashboardRfqsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-hotels': typeof ForHotelsRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/request-quote': typeof RequestQuoteRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/invitations': typeof AuthenticatedDashboardInvitationsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/hotel/$id': typeof AuthenticatedDashboardHotelIdRoute
  '/dashboard/rfqs/$id': typeof AuthenticatedDashboardRfqsIdRoute
  '/dashboard/rfqs/new': typeof AuthenticatedDashboardRfqsNewRoute
  '/dashboard/hotel': typeof AuthenticatedDashboardHotelIndexRoute
  '/dashboard/rfqs': typeof AuthenticatedDashboardRfqsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-hotels': typeof ForHotelsRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/request-quote': typeof RequestQuoteRoute
  '/requests': typeof RequestsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/hotels/$id': typeof HotelsIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/invitations': typeof AuthenticatedDashboardInvitationsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/hotel/$id': typeof AuthenticatedDashboardHotelIdRoute
  '/_authenticated/dashboard/rfqs/$id': typeof AuthenticatedDashboardRfqsIdRoute
  '/_authenticated/dashboard/rfqs/new': typeof AuthenticatedDashboardRfqsNewRoute
  '/_authenticated/dashboard/hotel/': typeof AuthenticatedDashboardHotelIndexRoute
  '/_authenticated/dashboard/rfqs/': typeof AuthenticatedDashboardRfqsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-hotels'
    | '/hotels'
    | '/how-it-works'
    | '/pricing'
    | '/request-quote'
    | '/requests'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/hotels/$id'
    | '/requests/$id'
    | '/dashboard/admin'
    | '/dashboard/invitations'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/dashboard/hotel/$id'
    | '/dashboard/rfqs/$id'
    | '/dashboard/rfqs/new'
    | '/dashboard/hotel/'
    | '/dashboard/rfqs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-hotels'
    | '/hotels'
    | '/how-it-works'
    | '/pricing'
    | '/request-quote'
    | '/requests'
    | '/reset-password'
    | '/sitemap.xml'
    | '/hotels/$id'
    | '/requests/$id'
    | '/dashboard/admin'
    | '/dashboard/invitations'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/hotel/$id'
    | '/dashboard/rfqs/$id'
    | '/dashboard/rfqs/new'
    | '/dashboard/hotel'
    | '/dashboard/rfqs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-hotels'
    | '/hotels'
    | '/how-it-works'
    | '/pricing'
    | '/request-quote'
    | '/requests'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/hotels/$id'
    | '/requests/$id'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/invitations'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/hotel/$id'
    | '/_authenticated/dashboard/rfqs/$id'
    | '/_authenticated/dashboard/rfqs/new'
    | '/_authenticated/dashboard/hotel/'
    | '/_authenticated/dashboard/rfqs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForHotelsRoute: typeof ForHotelsRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  RequestsRoute: typeof RequestsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-hotels': {
      id: '/for-hotels'
      path: '/for-hotels'
      fullPath: '/for-hotels'
      preLoaderRoute: typeof ForHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof RequestsRoute
    }
    '/hotels/$id': {
      id: '/hotels/$id'
      path: '/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof HotelsIdRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/invitations': {
      id: '/_authenticated/dashboard/invitations'
      path: '/invitations'
      fullPath: '/dashboard/invitations'
      preLoaderRoute: typeof AuthenticatedDashboardInvitationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rfqs/': {
      id: '/_authenticated/dashboard/rfqs/'
      path: '/rfqs'
      fullPath: '/dashboard/rfqs/'
      preLoaderRoute: typeof AuthenticatedDashboardRfqsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/hotel/': {
      id: '/_authenticated/dashboard/hotel/'
      path: '/hotel'
      fullPath: '/dashboard/hotel/'
      preLoaderRoute: typeof AuthenticatedDashboardHotelIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rfqs/new': {
      id: '/_authenticated/dashboard/rfqs/new'
      path: '/rfqs/new'
      fullPath: '/dashboard/rfqs/new'
      preLoaderRoute: typeof AuthenticatedDashboardRfqsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rfqs/$id': {
      id: '/_authenticated/dashboard/rfqs/$id'
      path: '/rfqs/$id'
      fullPath: '/dashboard/rfqs/$id'
      preLoaderRoute: typeof AuthenticatedDashboardRfqsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/hotel/$id': {
      id: '/_authenticated/dashboard/hotel/$id'
      path: '/hotel/$id'
      fullPath: '/dashboard/hotel/$id'
      preLoaderRoute: typeof AuthenticatedDashboardHotelIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardInvitationsRoute: typeof AuthenticatedDashboardInvitationsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardHotelIdRoute: typeof AuthenticatedDashboardHotelIdRoute
  AuthenticatedDashboardRfqsIdRoute: typeof AuthenticatedDashboardRfqsIdRoute
  AuthenticatedDashboardRfqsNewRoute: typeof AuthenticatedDashboardRfqsNewRoute
  AuthenticatedDashboardHotelIndexRoute: typeof AuthenticatedDashboardHotelIndexRoute
  AuthenticatedDashboardRfqsIndexRoute: typeof AuthenticatedDashboardRfqsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardInvitationsRoute:
      AuthenticatedDashboardInvitationsRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardHotelIdRoute: AuthenticatedDashboardHotelIdRoute,
    AuthenticatedDashboardRfqsIdRoute: AuthenticatedDashboardRfqsIdRoute,
    AuthenticatedDashboardRfqsNewRoute: AuthenticatedDashboardRfqsNewRoute,
    AuthenticatedDashboardHotelIndexRoute:
      AuthenticatedDashboardHotelIndexRoute,
    AuthenticatedDashboardRfqsIndexRoute: AuthenticatedDashboardRfqsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HotelsRouteChildren {
  HotelsIdRoute: typeof HotelsIdRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsIdRoute: HotelsIdRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

interface RequestsRouteChildren {
  RequestsIdRoute: typeof RequestsIdRoute
}

const RequestsRouteChildren: RequestsRouteChildren = {
  RequestsIdRoute: RequestsIdRoute,
}

const RequestsRouteWithChildren = RequestsRoute._addFileChildren(
  RequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForHotelsRoute: ForHotelsRoute,
  HotelsRoute: HotelsRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  RequestsRoute: RequestsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
