-- Global country/city UX support.
-- Extends existing lookup and text fields without migrating business records.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS city_name text;

ALTER TABLE public.profiles
  DROP CONSTRAINT IF EXISTS profiles_city_name_length_check;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_city_name_length_check
  CHECK (city_name IS NULL OR char_length(btrim(city_name)) BETWEEN 2 AND 100);

CREATE OR REPLACE FUNCTION public.restrict_profile_company_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _is_reviewer boolean :=
    public.has_role(auth.uid(), 'admin')
    OR public.has_permission(auth.uid(), 'manage_approvals');
BEGIN
  IF _is_reviewer THEN
    RETURN NEW;
  END IF;

  IF public.has_role(auth.uid(), 'hotel')
     AND (
       NEW.company_name IS DISTINCT FROM OLD.company_name
       OR NEW.vat_number IS DISTINCT FROM OLD.vat_number
       OR NEW.cr_number IS DISTINCT FROM OLD.cr_number
     ) THEN
    RAISE EXCEPTION 'Company name, VAT number, and CR number cannot be changed. Please contact support.';
  END IF;

  IF (
       auth.uid() IS DISTINCT FROM NEW.id
       OR COALESCE(OLD.agency_verification_status::text, 'draft')
          NOT IN ('draft', 'rejected')
     )
     AND (
       NEW.legal_company_name IS DISTINCT FROM OLD.legal_company_name
       OR NEW.company_name IS DISTINCT FROM OLD.company_name
       OR NEW.trade_name IS DISTINCT FROM OLD.trade_name
       OR NEW.country_id IS DISTINCT FROM OLD.country_id
       OR NEW.city_id IS DISTINCT FROM OLD.city_id
       OR NEW.city_name IS DISTINCT FROM OLD.city_name
       OR NEW.full_address IS DISTINCT FROM OLD.full_address
       OR NEW.website IS DISTINCT FROM OLD.website
       OR NEW.year_established IS DISTINCT FROM OLD.year_established
       OR NEW.employees_count IS DISTINCT FROM OLD.employees_count
       OR NEW.cr_number IS DISTINCT FROM OLD.cr_number
       OR NEW.cr_expiry_date IS DISTINCT FROM OLD.cr_expiry_date
       OR NEW.issuing_authority IS DISTINCT FROM OLD.issuing_authority
       OR NEW.tourism_license_number IS DISTINCT FROM OLD.tourism_license_number
       OR NEW.tourism_license_authority IS DISTINCT FROM OLD.tourism_license_authority
       OR NEW.cr_document_path IS DISTINCT FROM OLD.cr_document_path
       OR NEW.tourism_license_document_path IS DISTINCT FROM OLD.tourism_license_document_path
       OR NEW.contact_person_name IS DISTINCT FROM OLD.contact_person_name
       OR NEW.contact_person_position IS DISTINCT FROM OLD.contact_person_position
       OR NEW.contact_person_email IS DISTINCT FROM OLD.contact_person_email
       OR NEW.contact_person_phone IS DISTINCT FROM OLD.contact_person_phone
       OR NEW.contact_person_whatsapp IS DISTINCT FROM OLD.contact_person_whatsapp
       OR NEW.agency_type IS DISTINCT FROM OLD.agency_type
       OR NEW.annual_group_bookings IS DISTINCT FROM OLD.annual_group_bookings
       OR NEW.avg_rooms_per_booking IS DISTINCT FROM OLD.avg_rooms_per_booking
       OR NEW.legal_billing_name IS DISTINCT FROM OLD.legal_billing_name
       OR NEW.vat_billing_number IS DISTINCT FROM OLD.vat_billing_number
       OR NEW.billing_address IS DISTINCT FROM OLD.billing_address
       OR NEW.billing_email IS DISTINCT FROM OLD.billing_email
       OR NEW.legal_agreements_accepted_at IS DISTINCT FROM OLD.legal_agreements_accepted_at
       OR NEW.verification_submitted_at IS DISTINCT FROM OLD.verification_submitted_at
     ) THEN
    RAISE EXCEPTION 'Agency verification information cannot be changed while it is under review or verified.';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_agency_verification_submission()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _missing text[] := ARRAY[]::text[];
  _previous_status text := COALESCE(OLD.agency_verification_status::text, 'draft');
BEGIN
  IF auth.uid() = NEW.id
     AND NEW.agency_verification_status = 'pending_review'
     AND OLD.agency_verification_status IS DISTINCT FROM NEW.agency_verification_status THEN
    IF NOT public.has_role(NEW.id, 'organizer') THEN
      RAISE EXCEPTION 'Only agency account owners can submit agency verification';
    END IF;

    IF _previous_status NOT IN ('draft', 'rejected') THEN
      RAISE EXCEPTION 'Agency verification cannot be submitted from status %', _previous_status;
    END IF;

    IF NULLIF(btrim(COALESCE(NEW.legal_company_name, '')), '') IS NULL THEN _missing := _missing || 'Legal Company Name'; END IF;
    IF NEW.country_id IS NULL THEN _missing := _missing || 'Country'; END IF;
    IF NEW.city_id IS NULL
       AND (
         NULLIF(btrim(COALESCE(NEW.city_name, '')), '') IS NULL
         OR char_length(btrim(NEW.city_name)) NOT BETWEEN 2 AND 100
       ) THEN _missing := _missing || 'City'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.full_address, '')), '') IS NULL THEN _missing := _missing || 'Address'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.cr_number, '')), '') IS NULL THEN _missing := _missing || 'CR Number'; END IF;
    IF NEW.cr_expiry_date IS NULL THEN _missing := _missing || 'CR Expiry Date'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.issuing_authority, '')), '') IS NULL THEN _missing := _missing || 'Issuing Authority'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.cr_document_path, '')), '') IS NULL THEN _missing := _missing || 'Commercial Registration Document'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.contact_person_name, '')), '') IS NULL THEN _missing := _missing || 'Contact Name'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.contact_person_position, '')), '') IS NULL THEN _missing := _missing || 'Contact Position'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.contact_person_email, '')), '') IS NULL THEN _missing := _missing || 'Contact Email'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.contact_person_phone, '')), '') IS NULL THEN _missing := _missing || 'Contact Phone'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.agency_type, '')), '') IS NULL THEN _missing := _missing || 'Agency Type'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.annual_group_bookings, '')), '') IS NULL THEN _missing := _missing || 'Annual Group Bookings'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.avg_rooms_per_booking, '')), '') IS NULL THEN _missing := _missing || 'Average Rooms Per Booking'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.legal_billing_name, '')), '') IS NULL THEN _missing := _missing || 'Legal Billing Name'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.vat_billing_number, '')), '') IS NULL THEN _missing := _missing || 'VAT Number'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.billing_address, '')), '') IS NULL THEN _missing := _missing || 'Billing Address'; END IF;
    IF NULLIF(btrim(COALESCE(NEW.billing_email, '')), '') IS NULL THEN _missing := _missing || 'Billing Email'; END IF;
    IF NEW.legal_agreements_accepted_at IS NULL THEN _missing := _missing || 'Legal Agreements'; END IF;

    IF array_length(_missing, 1) > 0 THEN
      RAISE EXCEPTION 'Missing required fields: %', array_to_string(_missing, ', ');
    END IF;

    NEW.verification_submitted_at := now();
    NEW.verification_rejection_reason := NULL;

    INSERT INTO public.agency_verification_events (agency_id, event_type, actor_id)
    VALUES (
      NEW.id,
      CASE WHEN _previous_status = 'rejected' THEN 'resubmitted' ELSE 'submitted' END,
      NEW.id
    );
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_rfq_row()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.title IS NULL OR length(btrim(NEW.title)) < 3 THEN
    RAISE EXCEPTION 'Request title must be at least 3 characters';
  END IF;
  IF NEW.destination_country_id IS NULL THEN
    RAISE EXCEPTION 'Destination country is required';
  END IF;
  IF NEW.destination_city_id IS NULL
     AND (
       NULLIF(btrim(COALESCE(NEW.destination_city, '')), '') IS NULL
       OR char_length(btrim(NEW.destination_city)) NOT BETWEEN 2 AND 100
     ) THEN
    RAISE EXCEPTION 'Destination city is required';
  END IF;
  IF NEW.check_in IS NULL OR NEW.check_out IS NULL THEN
    RAISE EXCEPTION 'Check-in and check-out dates are required';
  END IF;
  IF NEW.check_out <= NEW.check_in THEN
    RAISE EXCEPTION 'Check-out must be after check-in';
  END IF;
  IF TG_OP = 'INSERT' AND NEW.check_in < CURRENT_DATE THEN
    RAISE EXCEPTION 'Check-in cannot be in the past';
  END IF;
  IF NEW.guests_count IS NULL OR NEW.guests_count < 1 OR NEW.guests_count > 100000 THEN
    RAISE EXCEPTION 'Guests count must be between 1 and 100000';
  END IF;
  IF NEW.rooms_needed IS NULL OR NEW.rooms_needed < 1 OR NEW.rooms_needed > 10000 THEN
    RAISE EXCEPTION 'Rooms needed must be between 1 and 10000';
  END IF;
  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.restrict_profile_company_fields()
FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_agency_verification_submission()
FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.validate_rfq_row()
FROM PUBLIC, anon, authenticated;

-- Major-city dataset derived from SimpleMaps World Cities (CC BY 4.0),
-- limited to the selected country's highest-population cities at runtime.
INSERT INTO public.cities (country_id, name_en, name_ar)
SELECT country.id, city.name_en, city.name_ar
FROM (VALUES
  ('SA', 'Riyadh', 'الرياض'),
  ('SA', 'Jeddah', 'جدة'),
  ('SA', 'Makkah', 'مكة المكرمة'),
  ('SA', 'Madinah', 'المدينة المنورة'),
  ('SA', 'Dammam', 'الدمام'),
  ('SA', 'Khobar', 'الخبر'),
  ('SA', 'Taif', 'الطائف'),
  ('SA', 'Abha', 'أبها'),
  ('SA', 'Tabuk', 'تبوك'),
  ('SA', 'Jazan', 'جازان'),
  ('SA', 'Al Hufuf', 'Al Hufūf'),
  ('SA', 'Hafr al Batin', 'Ḩafr al Bāţin'),
  ('SA', 'Al Hillah', 'Al Ḩillah'),
  ('SA', 'Al Qatif', 'Al Qaţīf'),
  ('SA', 'Buraydah', 'Buraydah'),
  ('SA', 'Al Jubayl', 'Al Jubayl'),
  ('SA', 'Ha''il', 'Ḩā’il'),
  ('SA', 'Al Kharj', 'Al Kharj'),
  ('SA', 'Al Qunfudhah', 'Al Qunfudhah'),
  ('SA', 'Al Mubarraz', 'Al Mubarraz'),
  ('EG', 'Cairo', 'القاهرة'),
  ('EG', 'Alexandria', 'الإسكندرية'),
  ('EG', 'Giza', 'الجيزة'),
  ('EG', 'Luxor', 'الأقصر'),
  ('EG', 'Aswan', 'أسوان'),
  ('EG', 'Hurghada', 'الغردقة'),
  ('EG', 'Sharm El Sheikh', 'شرم الشيخ'),
  ('EG', 'Mansoura', 'المنصورة'),
  ('EG', 'Tanta', 'طنطا'),
  ('EG', 'Ismailia', 'الإسماعيلية'),
  ('EG', 'Shubra al Khaymah', 'Shubrā al Khaymah'),
  ('EG', 'Halwan', 'Ḩalwān'),
  ('EG', 'Al Mahallah al Kubra', 'Al Maḩallah al Kubrá'),
  ('EG', 'Port Said', 'Port Said'),
  ('EG', 'Suez', 'Suez'),
  ('EG', 'Al `Ashir min Ramadan', 'Al ‘Āshir min Ramaḑān'),
  ('EG', 'Asyut', 'Asyūţ'),
  ('EG', 'Biba', 'Bibā'),
  ('EG', 'Ash Shuhada''', 'Ash Shuhadā’'),
  ('EG', 'Al Fayyum', 'Al Fayyūm'),
  ('EG', 'Az Zaqaziq', 'Az Zaqāzīq'),
  ('EG', 'Al `Ajami', 'Al ‘Ajamī'),
  ('EG', 'Al Matariyah', 'Al Maţarīyah'),
  ('EG', 'Kafr ad Dawwar', 'Kafr ad Dawwār'),
  ('EG', 'Damanhur', 'Damanhūr'),
  ('EG', 'Al Minya', 'Al Minyā'),
  ('EG', 'Mallawi', 'Mallawī'),
  ('EG', 'Damietta', 'Damietta'),
  ('EG', 'Timayy al Imdid', 'Timayy al Imdīd'),
  ('EG', 'Qina', 'Qinā'),
  ('AE', 'Dubai', 'دبي'),
  ('AE', 'Abu Dhabi', 'أبوظبي'),
  ('AE', 'Sharjah', 'الشارقة'),
  ('AE', 'Ajman', 'عجمان'),
  ('AE', 'Al Ain', 'العين'),
  ('AE', 'Ras Al Khaimah', 'رأس الخيمة'),
  ('AE', 'Fujairah', 'الفجيرة'),
  ('AE', 'Umm al Qaywayn', 'Umm al Qaywayn'),
  ('AE', 'Khawr Fakkan', 'Khawr Fakkān'),
  ('AE', 'Kalba', 'Kalbā'),
  ('AE', 'Madinat Zayid', 'Madīnat Zāyid'),
  ('AE', 'Al Jazirah al Hamra''', 'Al Jazīrah al Ḩamrā’'),
  ('QA', 'Doha', 'Doha'),
  ('QA', 'Ar Rayyan', 'Ar Rayyān'),
  ('QA', 'Al Khawr', 'Al Khawr'),
  ('QA', 'Ash Shihaniyah', 'Ash Shīḩānīyah'),
  ('QA', 'Al Wakrah', 'Al Wakrah'),
  ('QA', 'Umm Qurun', 'Umm Qurūn'),
  ('QA', 'Nu`ayjah', 'Nu‘ayjah'),
  ('QA', 'Adh Dhakhirah', 'Adh Dhakhīrah'),
  ('QA', 'Al Jumayliyah', 'Al Jumaylīyah'),
  ('QA', 'Umm Salal `Ali', 'Umm Şalāl ‘Alī'),
  ('BH', 'Manama', 'Manama'),
  ('BH', 'Al Muharraq', 'Al Muḩarraq'),
  ('BH', 'Madinat Hamad', 'Madīnat Ḩamad'),
  ('BH', 'Jidd Hafs', 'Jidd Ḩafş'),
  ('BH', 'Madinat `Isa', 'Madīnat ‘Īsá'),
  ('BH', 'Sitrah', 'Sitrah'),
  ('BH', 'Al Hamalah', 'Al Hamalah'),
  ('BH', 'Ad Diraz', 'Ad Dirāz'),
  ('BH', 'Al Malikiyah', 'Al Mālikīyah'),
  ('BH', 'Karranah', 'Karrānah'),
  ('KW', 'Kuwait City', 'مدينة الكويت'),
  ('KW', 'Al Ahmadi', 'الأحمدي'),
  ('KW', 'Hawalli', 'حولي'),
  ('KW', 'Salmiya', 'السالمية'),
  ('KW', 'Farwaniya', 'الفروانية'),
  ('KW', 'Jahra', 'الجهراء'),
  ('KW', 'Mubarak Al-Kabeer', 'مبارك الكبير'),
  ('KW', 'Fahaheel', 'الفحيحيل'),
  ('KW', 'Mangaf', 'المنقف'),
  ('KW', 'Sabah Al-Salem', 'صباح السالم'),
  ('OM', 'Muscat', 'Muscat'),
  ('OM', 'Bawshar', 'Bawshar'),
  ('OM', 'As Sib', 'As Sīb'),
  ('OM', 'Matrah', 'Maţraḩ'),
  ('OM', 'Salalah', 'Şalālah'),
  ('OM', 'As Suwayq', 'As Suwayq'),
  ('OM', 'As Suwayhirah as Sahil', 'Aş Şuwayḩirah as Sāḩil'),
  ('OM', 'Ar Rustaq', 'Ar Rustāq'),
  ('OM', 'Al Mudaybi', 'Al Muḑaybī'),
  ('OM', '`Ibri', '‘Ibrī'),
  ('OM', 'Bahla''', 'Bahlā’'),
  ('OM', 'Sama''il', 'Samā’il'),
  ('OM', 'Nizwa', 'Nizwá'),
  ('OM', 'Al `Amirat', 'Al ‘Āmirāt'),
  ('OM', 'Al Buraymi', 'Al Buraymī'),
  ('OM', 'Qurayyat', 'Qurayyāt'),
  ('OM', 'Al Madrah Sama''il', 'Al Madrah Samā’il'),
  ('OM', 'Shinas', 'Shināş'),
  ('OM', 'Izki', 'Izkī'),
  ('OM', 'Ibra''', 'Ibrā’'),
  ('JO', 'Amman', 'Amman'),
  ('JO', 'Al Mafraq', 'Al Mafraq'),
  ('JO', 'Irbid', 'Irbid'),
  ('JO', 'Az Zarqa''', 'Az Zarqā’'),
  ('JO', 'Ar Rusayfah', 'Ar Ruşayfah'),
  ('JO', 'Sahab', 'Saḩāb'),
  ('JO', 'Ar Ramtha', 'Ar Ramthā'),
  ('JO', '`Ajlun', '‘Ajlūn'),
  ('JO', 'Al `Aqabah', 'Al ‘Aqabah'),
  ('JO', 'Al Jizah', 'Al Jīzah'),
  ('JO', 'As Salt', 'As Salţ'),
  ('JO', 'Madaba', 'Mādabā'),
  ('JO', 'Jarash', 'Jarash'),
  ('JO', 'Ma`an', 'Ma‘ān'),
  ('JO', 'Al Hisn', 'Al Ḩişn'),
  ('JO', 'At Turrah', 'Aţ Ţurrah'),
  ('JO', 'Dayr Abu Sa`id', 'Dayr Abū Sa‘īd'),
  ('JO', 'AshShajarah', 'AshShajarah'),
  ('JO', 'Mu''tah', 'Mu’tah'),
  ('JO', 'Ash Shunah ash Shamaliyah', 'Ash Shūnah ash Shamālīyah'),
  ('TR', 'Istanbul', 'إسطنبول'),
  ('TR', 'Ankara', 'أنقرة'),
  ('TR', 'Izmir', 'إزمير'),
  ('TR', 'Antalya', 'أنطاليا'),
  ('TR', 'Bursa', 'Bursa'),
  ('TR', 'Konya', 'Konya'),
  ('TR', 'Gaziantep', 'Gaziantep'),
  ('TR', 'Sanliurfa', 'Şanlıurfa'),
  ('TR', 'Mersin', 'Mersin'),
  ('TR', 'Adana', 'Adana'),
  ('TR', 'Diyarbakir', 'Diyarbakır'),
  ('TR', 'Kayseri', 'Kayseri'),
  ('TR', 'Samsun', 'Samsun'),
  ('TR', 'Akcaabat', 'Akçaabat'),
  ('TR', 'Denizli', 'Denizli'),
  ('TR', 'Cankaya', 'Çankaya'),
  ('TR', 'Esenyurt', 'Esenyurt'),
  ('TR', 'Eskisehir', 'Eskişehir'),
  ('TR', 'Seyhan', 'Seyhan'),
  ('TR', 'Kucukcekmece', 'Küçükçekmece'),
  ('TR', 'Erzurum', 'Erzurum'),
  ('TR', 'Bagcilar', 'Bağcılar'),
  ('TR', 'Pendik', 'Pendik'),
  ('TR', 'Selcuklu', 'Selçuklu'),
  ('TR', 'Yildirim', 'Yıldırım'),
  ('TR', 'Kartal', 'Kartal'),
  ('TR', 'Batman', 'Batman'),
  ('TR', 'Esenler', 'Esenler'),
  ('TR', 'Kahramanmaras', 'Kahramanmaraş'),
  ('TR', 'Kagithane', 'Kâğıthane'),
  ('MA', 'Casablanca', 'Casablanca'),
  ('MA', 'El Kelaa des Srarhna', 'El Kelaa des Srarhna'),
  ('MA', 'Fes', 'Fès'),
  ('MA', 'Tangier', 'Tangier'),
  ('MA', 'Marrakech', 'Marrakech'),
  ('MA', 'Sale', 'Sale'),
  ('MA', 'Mediouna', 'Mediouna'),
  ('MA', 'Rabat', 'Rabat'),
  ('MA', 'Meknes', 'Meknès'),
  ('MA', 'Oujda-Angad', 'Oujda-Angad'),
  ('MA', 'Kenitra', 'Kenitra'),
  ('MA', 'Agadir', 'Agadir'),
  ('MA', 'Tetouan', 'Tétouan'),
  ('MA', 'Taourirt', 'Taourirt'),
  ('MA', 'Temara', 'Temara'),
  ('MA', 'Safi', 'Safi'),
  ('MA', 'Khenifra', 'Khénifra'),
  ('MA', 'Laayoune', 'Laâyoune'),
  ('MA', 'Mohammedia', 'Mohammedia'),
  ('MA', 'Kouribga', 'Kouribga'),
  ('GB', 'London', 'لندن'),
  ('GB', 'Manchester', 'مانشستر'),
  ('GB', 'Birmingham', 'برمنغهام'),
  ('GB', 'Liverpool', 'Liverpool'),
  ('GB', 'Portsmouth', 'Portsmouth'),
  ('GB', 'Southampton', 'Southampton'),
  ('GB', 'Leeds', 'Leeds'),
  ('GB', 'Nottingham', 'Nottingham'),
  ('GB', 'Glasgow', 'Glasgow'),
  ('GB', 'Bristol', 'Bristol'),
  ('GB', 'Sheffield', 'Sheffield'),
  ('GB', 'Leicester', 'Leicester'),
  ('GB', 'Edinburgh', 'Edinburgh'),
  ('GB', 'Caerdydd', 'Caerdydd'),
  ('GB', 'Worthing', 'Worthing'),
  ('GB', 'Stoke-on-Trent', 'Stoke-on-Trent'),
  ('GB', 'Coventry', 'Coventry'),
  ('GB', 'Reading', 'Reading'),
  ('GB', 'Belfast', 'Belfast'),
  ('GB', 'Kingston upon Hull', 'Kingston upon Hull'),
  ('GB', 'Newcastle', 'Newcastle'),
  ('GB', 'Stockport', 'Stockport'),
  ('GB', 'Bradford', 'Bradford'),
  ('GB', 'Ipswich', 'Ipswich'),
  ('GB', 'Bolton', 'Bolton'),
  ('GB', 'Sunderland', 'Sunderland'),
  ('GB', 'Plymouth', 'Plymouth'),
  ('GB', 'Derby', 'Derby'),
  ('GB', 'Westminster', 'Westminster'),
  ('GB', 'Wolverhampton', 'Wolverhampton'),
  ('US', 'New York', 'نيويورك'),
  ('US', 'Los Angeles', 'لوس أنجلوس'),
  ('US', 'Chicago', 'شيكاغو'),
  ('US', 'Miami', 'Miami'),
  ('US', 'Dallas', 'Dallas'),
  ('US', 'Houston', 'Houston'),
  ('US', 'Philadelphia', 'Philadelphia'),
  ('US', 'Atlanta', 'Atlanta'),
  ('US', 'Washington', 'Washington'),
  ('US', 'Boston', 'Boston'),
  ('US', 'Phoenix', 'Phoenix'),
  ('US', 'Detroit', 'Detroit'),
  ('US', 'Seattle', 'Seattle'),
  ('US', 'San Francisco', 'San Francisco'),
  ('US', 'San Diego', 'San Diego'),
  ('US', 'Minneapolis', 'Minneapolis'),
  ('US', 'Brooklyn', 'Brooklyn'),
  ('US', 'Tampa', 'Tampa'),
  ('US', 'Denver', 'Denver'),
  ('US', 'Queens', 'Queens'),
  ('US', 'Baltimore', 'Baltimore'),
  ('US', 'Las Vegas', 'Las Vegas'),
  ('US', 'St. Louis', 'St. Louis'),
  ('US', 'Portland', 'Portland'),
  ('US', 'Riverside', 'Riverside'),
  ('US', 'Orlando', 'Orlando'),
  ('US', 'Sacramento', 'Sacramento'),
  ('US', 'San Antonio', 'San Antonio'),
  ('US', 'San Jose', 'San Jose'),
  ('US', 'Pittsburgh', 'Pittsburgh'),
  ('FR', 'Paris', 'Paris'),
  ('FR', 'Marseille', 'Marseille'),
  ('FR', 'Lyon', 'Lyon'),
  ('FR', 'Toulouse', 'Toulouse'),
  ('FR', 'Nice', 'Nice'),
  ('FR', 'Nantes', 'Nantes'),
  ('FR', 'Montpellier', 'Montpellier'),
  ('FR', 'Strasbourg', 'Strasbourg'),
  ('FR', 'Bordeaux', 'Bordeaux'),
  ('FR', 'Lille', 'Lille'),
  ('FR', 'Rennes', 'Rennes'),
  ('FR', 'Reims', 'Reims'),
  ('FR', 'Toulon', 'Toulon'),
  ('FR', 'Saint-Etienne', 'Saint-Étienne'),
  ('FR', 'Le Havre', 'Le Havre'),
  ('FR', 'Grenoble', 'Grenoble'),
  ('FR', 'Dijon', 'Dijon'),
  ('FR', 'Angers', 'Angers'),
  ('FR', 'Villeurbanne', 'Villeurbanne'),
  ('FR', 'Nimes', 'Nîmes'),
  ('FR', 'Clermont-Ferrand', 'Clermont-Ferrand'),
  ('FR', 'Aix-en-Provence', 'Aix-en-Provence'),
  ('FR', 'Le Mans', 'Le Mans'),
  ('FR', 'Brest', 'Brest'),
  ('FR', 'Tours', 'Tours'),
  ('FR', 'Amiens', 'Amiens'),
  ('FR', 'Limoges', 'Limoges'),
  ('FR', 'Annecy', 'Annecy'),
  ('FR', 'Boulogne-Billancourt', 'Boulogne-Billancourt'),
  ('FR', 'Perpignan', 'Perpignan'),
  ('DE', 'Berlin', 'Berlin'),
  ('DE', 'Stuttgart', 'Stuttgart'),
  ('DE', 'Munich', 'Munich'),
  ('DE', 'Hamburg', 'Hamburg'),
  ('DE', 'Cologne', 'Cologne'),
  ('DE', 'Frankfurt', 'Frankfurt'),
  ('DE', 'Dusseldorf', 'Düsseldorf'),
  ('DE', 'Leipzig', 'Leipzig'),
  ('DE', 'Dortmund', 'Dortmund'),
  ('DE', 'Essen', 'Essen'),
  ('DE', 'Bremen', 'Bremen'),
  ('DE', 'Dresden', 'Dresden'),
  ('DE', 'Hannover', 'Hannover'),
  ('DE', 'Nuremberg', 'Nuremberg'),
  ('DE', 'Duisburg', 'Duisburg'),
  ('DE', 'Bochum', 'Bochum'),
  ('DE', 'Wuppertal', 'Wuppertal'),
  ('DE', 'Bielefeld', 'Bielefeld'),
  ('DE', 'Bonn', 'Bonn'),
  ('DE', 'Munster', 'Münster'),
  ('DE', 'Mannheim', 'Mannheim'),
  ('DE', 'Karlsruhe', 'Karlsruhe'),
  ('DE', 'Augsburg', 'Augsburg'),
  ('DE', 'Wiesbaden', 'Wiesbaden'),
  ('DE', 'Monchengladbach', 'Mönchengladbach'),
  ('DE', 'Gelsenkirchen', 'Gelsenkirchen'),
  ('DE', 'Aachen', 'Aachen'),
  ('DE', 'Braunschweig', 'Braunschweig'),
  ('DE', 'Chemnitz', 'Chemnitz'),
  ('DE', 'Kiel', 'Kiel'),
  ('IT', 'Rome', 'Rome'),
  ('IT', 'Milan', 'Milan'),
  ('IT', 'Naples', 'Naples'),
  ('IT', 'Turin', 'Turin'),
  ('IT', 'Palermo', 'Palermo'),
  ('IT', 'Genoa', 'Genoa'),
  ('IT', 'Bologna', 'Bologna'),
  ('IT', 'Florence', 'Florence'),
  ('IT', 'Bari', 'Bari'),
  ('IT', 'Catania', 'Catania'),
  ('IT', 'Venice', 'Venice'),
  ('IT', 'Verona', 'Verona'),
  ('IT', 'Messina', 'Messina'),
  ('IT', 'Padova', 'Padova'),
  ('IT', 'Trieste', 'Trieste'),
  ('IT', 'Cosenza', 'Cosenza'),
  ('IT', 'Taranto', 'Taranto'),
  ('IT', 'Brescia', 'Brescia'),
  ('IT', 'Parma', 'Parma'),
  ('IT', 'Prato', 'Prato'),
  ('ES', 'Madrid', 'Madrid'),
  ('ES', 'Barcelona', 'Barcelona'),
  ('ES', 'Sevilla', 'Sevilla'),
  ('ES', 'Malaga', 'Málaga'),
  ('ES', 'Valencia', 'Valencia'),
  ('ES', 'Bilbao', 'Bilbao'),
  ('ES', 'Zaragoza', 'Zaragoza'),
  ('ES', 'Murcia', 'Murcia'),
  ('ES', 'Palma', 'Palma'),
  ('ES', 'Las Palmas', 'Las Palmas'),
  ('ES', 'Alicante', 'Alicante'),
  ('ES', 'Cordoba', 'Córdoba'),
  ('ES', 'Valladolid', 'Valladolid'),
  ('ES', 'Vigo', 'Vigo'),
  ('ES', 'Gijon', 'Gijón'),
  ('ES', 'Vitoria-Gasteiz', 'Vitoria-Gasteiz'),
  ('ES', 'A Coruna', 'A Coruña'),
  ('ES', 'Elche', 'Elche'),
  ('ES', 'Granada', 'Granada'),
  ('ES', 'Tarrasa', 'Tarrasa'),
  ('NL', 'Amsterdam', 'Amsterdam'),
  ('NL', 'Rotterdam', 'Rotterdam'),
  ('NL', 'The Hague', 'The Hague'),
  ('NL', 'Utrecht', 'Utrecht'),
  ('NL', 'Maastricht', 'Maastricht'),
  ('NL', 'Eindhoven', 'Eindhoven'),
  ('NL', 'Groningen', 'Groningen'),
  ('NL', 'Tilburg', 'Tilburg'),
  ('NL', 'Almere', 'Almere'),
  ('NL', 'Breda', 'Breda'),
  ('NL', 'Nijmegen', 'Nijmegen'),
  ('NL', 'Arnhem', 'Arnhem'),
  ('NL', 'Haarlem', 'Haarlem'),
  ('NL', 'Apeldoorn', 'Apeldoorn'),
  ('NL', 'Enschede', 'Enschede'),
  ('NL', 'Hoofddorp', 'Hoofddorp'),
  ('NL', '''s-Hertogenbosch', '’s-Hertogenbosch'),
  ('NL', 'Amersfoort', 'Amersfoort'),
  ('NL', 'Zaanstad', 'Zaanstad'),
  ('NL', 'Zwolle', 'Zwolle'),
  ('BE', 'Brussels', 'Brussels'),
  ('BE', 'Antwerp', 'Antwerp'),
  ('BE', 'Gent', 'Gent'),
  ('BE', 'Charleroi', 'Charleroi'),
  ('BE', 'Liege', 'Liège'),
  ('BE', 'Anderlecht', 'Anderlecht'),
  ('BE', 'Bruges', 'Bruges'),
  ('BE', 'Namur', 'Namur'),
  ('BE', 'Leuven', 'Leuven'),
  ('BE', 'Moortebeek', 'Moortebeek'),
  ('BE', 'Mons', 'Mons'),
  ('BE', 'Aalst', 'Aalst'),
  ('BE', 'Mechelen', 'Mechelen'),
  ('BE', 'La Louviere', 'La Louvière'),
  ('BE', 'Deurne', 'Deurne'),
  ('BE', 'Sint-Niklaas', 'Sint-Niklaas'),
  ('BE', 'Kortrijk', 'Kortrijk'),
  ('BE', 'Hasselt', 'Hasselt'),
  ('BE', 'Ostend', 'Ostend'),
  ('BE', 'Tournai', 'Tournai'),
  ('CH', 'Zurich', 'Zürich'),
  ('CH', 'Geneva', 'Geneva'),
  ('CH', 'Basel', 'Basel'),
  ('CH', 'Lausanne', 'Lausanne'),
  ('CH', 'Bern', 'Bern'),
  ('CH', 'Winterthur', 'Winterthur'),
  ('CH', 'Lucerne', 'Lucerne'),
  ('CH', 'Sankt Gallen', 'Sankt Gallen'),
  ('CH', 'Lugano', 'Lugano'),
  ('CH', 'Biel/Bienne', 'Biel/Bienne'),
  ('CH', 'Thun', 'Thun'),
  ('CH', 'Bellinzona', 'Bellinzona'),
  ('CH', 'Koniz', 'Köniz'),
  ('CH', 'La Chaux-de-Fonds', 'La Chaux-de-Fonds'),
  ('CH', 'Fribourg', 'Fribourg'),
  ('CH', 'Uster', 'Uster'),
  ('CH', 'Schaffhausen', 'Schaffhausen'),
  ('CH', 'Vernier', 'Vernier'),
  ('CH', 'Chur', 'Chur'),
  ('CH', 'Sion', 'Sion'),
  ('SE', 'Stockholm', 'Stockholm'),
  ('SE', 'Gothenburg', 'Gothenburg'),
  ('SE', 'Malmo', 'Malmö'),
  ('SE', 'Uppsala', 'Uppsala'),
  ('SE', 'Norrkoping', 'Norrköping'),
  ('SE', 'Vasteras', 'Västerås'),
  ('SE', 'Orebro', 'Örebro'),
  ('SE', 'Linkoping', 'Linköping'),
  ('SE', 'Helsingborg', 'Helsingborg'),
  ('SE', 'Jonkoping', 'Jönköping'),
  ('SE', 'Vimmerby', 'Vimmerby'),
  ('SE', 'Sundsvall', 'Sundsvall'),
  ('SE', 'Gavle', 'Gävle'),
  ('SE', 'Umea', 'Umeå'),
  ('SE', 'Skelleftea', 'Skellefteå'),
  ('SE', 'Karlstad', 'Karlstad'),
  ('SE', 'Sodertalje', 'Södertälje'),
  ('SE', 'Halmstad', 'Halmstad'),
  ('SE', 'Eskilstuna', 'Eskilstuna'),
  ('SE', 'Karlskrona', 'Karlskrona'),
  ('NO', 'Oslo', 'Oslo'),
  ('NO', 'Bergen', 'Bergen'),
  ('NO', 'Stavanger', 'Stavanger'),
  ('NO', 'Sandnes', 'Sandnes'),
  ('NO', 'Trondheim', 'Trondheim'),
  ('NO', 'Sandvika', 'Sandvika'),
  ('NO', 'Kristiansand', 'Kristiansand'),
  ('NO', 'Drammen', 'Drammen'),
  ('NO', 'Fredrikstad', 'Fredrikstad'),
  ('NO', 'Sandefjord', 'Sandefjord'),
  ('NO', 'Asker', 'Asker'),
  ('NO', 'Nordre Fale', 'Nordre Fåle'),
  ('NO', 'Tonsberg', 'Tønsberg'),
  ('NO', 'Skien', 'Skien'),
  ('NO', 'Sarpsborg', 'Sarpsborg'),
  ('NO', 'Bodo', 'Bodø'),
  ('NO', 'Alesund', 'Ålesund'),
  ('NO', 'Moss', 'Moss'),
  ('NO', 'Arendal', 'Arendal'),
  ('NO', 'Lorenskog', 'Lørenskog'),
  ('DK', 'Copenhagen', 'Copenhagen'),
  ('DK', 'Aarhus', 'Aarhus'),
  ('DK', 'Odense', 'Odense'),
  ('DK', 'Aalborg', 'Aalborg'),
  ('DK', 'Esbjerg', 'Esbjerg'),
  ('DK', 'Randers', 'Randers'),
  ('DK', 'Kolding', 'Kolding'),
  ('DK', 'Horsens', 'Horsens'),
  ('DK', 'Vejle', 'Vejle'),
  ('DK', 'Roskilde', 'Roskilde'),
  ('DK', 'Herning', 'Herning'),
  ('DK', 'Silkeborg', 'Silkeborg'),
  ('DK', 'Horsholm', 'Hørsholm'),
  ('DK', 'Helsingor', 'Helsingør'),
  ('DK', 'Naestved', 'Næstved'),
  ('DK', 'Viborg', 'Viborg'),
  ('DK', 'Fredericia', 'Fredericia'),
  ('DK', 'Koge', 'Køge'),
  ('DK', 'Holstebro', 'Holstebro'),
  ('DK', 'Hillerod', 'Hillerød'),
  ('FI', 'Helsinki', 'Helsinki'),
  ('FI', 'Tampere', 'Tampere'),
  ('FI', 'Espoo', 'Espoo'),
  ('FI', 'Turku', 'Turku'),
  ('FI', 'Vantaa', 'Vantaa'),
  ('FI', 'Oulu', 'Oulu'),
  ('FI', 'Jyvaskyla', 'Jyväskylä'),
  ('FI', 'Kuopio', 'Kuopio'),
  ('FI', 'Lahti', 'Lahti'),
  ('FI', 'Kouvola', 'Kouvola'),
  ('FI', 'Pori', 'Pori'),
  ('FI', 'Joensuu', 'Joensuu'),
  ('FI', 'Lappeenranta', 'Lappeenranta'),
  ('FI', 'Hameenlinna', 'Hämeenlinna'),
  ('FI', 'Vaasa', 'Vaasa'),
  ('FI', 'Seinajoki', 'Seinäjoki'),
  ('FI', 'Rovaniemi', 'Rovaniemi'),
  ('FI', 'Mikkeli', 'Mikkeli'),
  ('FI', 'Kotka', 'Kotka'),
  ('FI', 'Salo', 'Salo'),
  ('IE', 'Dublin', 'Dublin'),
  ('IE', 'Finglas', 'Finglas'),
  ('IE', 'Cork', 'Cork'),
  ('IE', 'Tallaght', 'Tallaght'),
  ('IE', 'Galway', 'Galway'),
  ('IE', 'Limerick', 'Limerick'),
  ('IE', 'Lucan', 'Lucan'),
  ('IE', 'Waterford', 'Waterford'),
  ('IE', 'Clondalkin', 'Clondalkin'),
  ('IE', 'Drogheda', 'Drogheda'),
  ('IE', 'Dun Dealgan', 'Dún Dealgan'),
  ('IE', 'Swords', 'Swords'),
  ('IE', 'Navan', 'Navan'),
  ('IE', 'Blackrock', 'Blackrock'),
  ('IE', 'Douglas', 'Douglas'),
  ('IE', 'Ennis', 'Ennis'),
  ('IE', 'Carlow', 'Carlow'),
  ('IE', 'Dunleary', 'Dunleary'),
  ('IE', 'Tralee', 'Tralee'),
  ('IE', 'Ashtown', 'Ashtown'),
  ('PT', 'Lisbon', 'Lisbon'),
  ('PT', 'Porto', 'Porto'),
  ('PT', 'Aves', 'Aves'),
  ('PT', 'Sintra', 'Sintra'),
  ('PT', 'Vila Nova de Gaia', 'Vila Nova de Gaia'),
  ('PT', 'Cascais', 'Cascais'),
  ('PT', 'Loures', 'Loures'),
  ('PT', 'Braga', 'Braga'),
  ('PT', 'Almada', 'Almada'),
  ('PT', 'Matosinhos', 'Matosinhos'),
  ('PT', 'Amadora', 'Amadora'),
  ('PT', 'Oeiras', 'Oeiras'),
  ('PT', 'Gondomar', 'Gondomar'),
  ('PT', 'Seixal', 'Seixal'),
  ('PT', 'Guimaraes', 'Guimarães'),
  ('PT', 'Odivelas', 'Odivelas'),
  ('PT', 'Coimbra', 'Coimbra'),
  ('PT', 'Vila Franca de Xira', 'Vila Franca de Xira'),
  ('PT', 'Maia', 'Maia'),
  ('PT', 'Famalicao', 'Famalicão'),
  ('AT', 'Vienna', 'Vienna'),
  ('AT', 'Graz', 'Graz'),
  ('AT', 'Linz', 'Linz'),
  ('AT', 'Salzburg', 'Salzburg'),
  ('AT', 'Innsbruck', 'Innsbruck'),
  ('AT', 'Klagenfurt', 'Klagenfurt'),
  ('AT', 'Villach', 'Villach'),
  ('AT', 'Wels', 'Wels'),
  ('AT', 'Sankt Polten', 'Sankt Pölten'),
  ('AT', 'Dornbirn', 'Dornbirn'),
  ('AT', 'Wiener Neustadt', 'Wiener Neustadt'),
  ('AT', 'Steyr', 'Steyr'),
  ('AT', 'Bregenz', 'Bregenz'),
  ('AT', 'Leonding', 'Leonding'),
  ('AT', 'Klosterneuburg', 'Klosterneuburg'),
  ('AT', 'Baden', 'Baden'),
  ('AT', 'Wolfsberg', 'Wolfsberg'),
  ('AT', 'Leoben', 'Leoben'),
  ('AT', 'Krems an der Donau', 'Krems an der Donau'),
  ('AT', 'Traun', 'Traun'),
  ('GR', 'Athens', 'Athens'),
  ('GR', 'Thessaloniki', 'Thessaloníki'),
  ('GR', 'Piraeus', 'Piraeus'),
  ('GR', 'Irakleio', 'Irákleio'),
  ('GR', 'Patra', 'Pátra'),
  ('GR', 'Larisa', 'Lárisa'),
  ('GR', 'Volos', 'Vólos'),
  ('GR', 'Peristeri', 'Peristéri'),
  ('GR', 'Ioannina', 'Ioánnina'),
  ('GR', 'Acharnes', 'Acharnés'),
  ('GR', 'Kallithea', 'Kallithéa'),
  ('GR', 'Kalamaria', 'Kalamariá'),
  ('GR', 'Nikaia', 'Níkaia'),
  ('GR', 'Glyfada', 'Glyfáda'),
  ('GR', 'Ilion', 'Ílion'),
  ('GR', 'Katerini', 'Kateríni'),
  ('GR', 'Ilioupoli', 'Ilioúpoli'),
  ('GR', 'Keratsini', 'Keratsíni'),
  ('GR', 'Evosmos', 'Évosmos'),
  ('GR', 'Chalandri', 'Chalándri'),
  ('PL', 'Warsaw', 'Warsaw'),
  ('PL', 'Krakow', 'Kraków'),
  ('PL', 'Lodz', 'Łódź'),
  ('PL', 'Wroclaw', 'Wrocław'),
  ('PL', 'Poznan', 'Poznań'),
  ('PL', 'Gdansk', 'Gdańsk'),
  ('PL', 'Szczecin', 'Szczecin'),
  ('PL', 'Bydgoszcz', 'Bydgoszcz'),
  ('PL', 'Lublin', 'Lublin'),
  ('PL', 'Bielsko-Biala', 'Bielsko-Biała'),
  ('PL', 'Bialystok', 'Białystok'),
  ('PL', 'Katowice', 'Katowice'),
  ('PL', 'Gdynia', 'Gdynia'),
  ('PL', 'Czestochowa', 'Częstochowa'),
  ('PL', 'Radom', 'Radom'),
  ('PL', 'Zielona Gora', 'Zielona Góra'),
  ('PL', 'Torun', 'Toruń'),
  ('PL', 'Rzeszow', 'Rzeszów'),
  ('PL', 'Sosnowiec', 'Sosnowiec'),
  ('PL', 'Kielce', 'Kielce'),
  ('RU', 'Moscow', 'Moscow'),
  ('RU', 'Saint Petersburg', 'Saint Petersburg'),
  ('RU', 'Novosibirsk', 'Novosibirsk'),
  ('RU', 'Yekaterinburg', 'Yekaterinburg'),
  ('RU', 'Nizhniy Novgorod', 'Nizhniy Novgorod'),
  ('RU', 'Kazan', 'Kazan'),
  ('RU', 'Chelyabinsk', 'Chelyabinsk'),
  ('RU', 'Omsk', 'Omsk'),
  ('RU', 'Samara', 'Samara'),
  ('RU', 'Rostov', 'Rostov'),
  ('RU', 'Ufa', 'Ufa'),
  ('RU', 'Krasnoyarsk', 'Krasnoyarsk'),
  ('RU', 'Voronezh', 'Voronezh'),
  ('RU', 'Perm', 'Perm'),
  ('RU', 'Volgograd', 'Volgograd'),
  ('RU', 'Krasnodar', 'Krasnodar'),
  ('RU', 'Saratov', 'Saratov'),
  ('RU', 'Tyumen', 'Tyumen'),
  ('RU', 'Tolyatti', 'Tolyatti'),
  ('RU', 'Izhevsk', 'Izhevsk'),
  ('RU', 'Barnaul', 'Barnaul'),
  ('RU', 'Ulyanovsk', 'Ulyanovsk'),
  ('RU', 'Irkutsk', 'Irkutsk'),
  ('RU', 'Khabarovsk', 'Khabarovsk'),
  ('RU', 'Yaroslavl', 'Yaroslavl'),
  ('RU', 'Vladivostok', 'Vladivostok'),
  ('RU', 'Makhachkala', 'Makhachkala'),
  ('RU', 'Tomsk', 'Tomsk'),
  ('RU', 'Orenburg', 'Orenburg'),
  ('RU', 'Kemerovo', 'Kemerovo'),
  ('UA', 'Kyiv', 'Kyiv'),
  ('UA', 'Kharkiv', 'Kharkiv'),
  ('UA', 'Odesa', 'Odesa'),
  ('UA', 'Dnipro', 'Dnipro'),
  ('UA', 'Donetsk', 'Donetsk'),
  ('UA', 'Zaporizhzhia', 'Zaporizhzhia'),
  ('UA', 'Lviv', 'Lviv'),
  ('UA', 'Kryvyi Rih', 'Kryvyi Rih'),
  ('UA', 'Sevastopol', 'Sevastopol'),
  ('UA', 'Mykolaiv', 'Mykolaiv'),
  ('UA', 'Mariupol', 'Mariupol'),
  ('UA', 'Luhansk', 'Luhansk'),
  ('UA', 'Vinnytsia', 'Vinnytsia'),
  ('UA', 'Makiivka', 'Makiivka'),
  ('UA', 'Simferopol', 'Simferopol'),
  ('UA', 'Poltava', 'Poltava'),
  ('UA', 'Chernihiv', 'Chernihiv'),
  ('UA', 'Kherson', 'Kherson'),
  ('UA', 'Cherkasy', 'Cherkasy'),
  ('UA', 'Khmelnytskyi', 'Khmelnytskyi'),
  ('CA', 'Toronto', 'Toronto'),
  ('CA', 'Montreal', 'Montréal'),
  ('CA', 'Vancouver', 'Vancouver'),
  ('CA', 'Calgary', 'Calgary'),
  ('CA', 'Edmonton', 'Edmonton'),
  ('CA', 'Ottawa', 'Ottawa'),
  ('CA', 'Mississauga', 'Mississauga'),
  ('CA', 'Winnipeg', 'Winnipeg'),
  ('CA', 'Quebec City', 'Quebec City'),
  ('CA', 'Hamilton', 'Hamilton'),
  ('CA', 'Brampton', 'Brampton'),
  ('CA', 'Surrey', 'Surrey'),
  ('CA', 'Kitchener', 'Kitchener'),
  ('CA', 'Laval', 'Laval'),
  ('CA', 'Halifax', 'Halifax'),
  ('CA', 'London', 'London'),
  ('CA', 'Victoria', 'Victoria'),
  ('CA', 'Markham', 'Markham'),
  ('CA', 'St. Catharines', 'St. Catharines'),
  ('CA', 'Niagara Falls', 'Niagara Falls'),
  ('MX', 'Mexico City', 'Mexico City'),
  ('MX', 'Guadalajara', 'Guadalajara'),
  ('MX', 'Monterrey', 'Monterrey'),
  ('MX', 'Tijuana', 'Tijuana'),
  ('MX', 'Ecatepec', 'Ecatepec'),
  ('MX', 'Leon de los Aldama', 'León de los Aldama'),
  ('MX', 'Puebla', 'Puebla'),
  ('MX', 'Zapopan', 'Zapopan'),
  ('MX', 'Juarez', 'Juárez'),
  ('MX', 'Ciudad Nezahualcoyotl', 'Ciudad Nezahualcóyotl'),
  ('MX', 'Mexicali', 'Mexicali'),
  ('MX', 'Nezahualcoyotl', 'Nezahualcóyotl'),
  ('MX', 'Morelia', 'Morelia'),
  ('MX', 'Aguascalientes', 'Aguascalientes'),
  ('MX', 'Naucalpan de Juarez', 'Naucalpan de Juárez'),
  ('MX', 'Merida', 'Mérida'),
  ('MX', 'Cancun', 'Cancún'),
  ('MX', 'Chihuahua', 'Chihuahua'),
  ('MX', 'Saltillo', 'Saltillo'),
  ('MX', 'Hermosillo', 'Hermosillo'),
  ('MX', 'Culiacan', 'Culiacán'),
  ('MX', 'Queretaro', 'Querétaro'),
  ('MX', 'San Luis Potosi', 'San Luis Potosí'),
  ('MX', 'Tlajomulco de Zuniga', 'Tlajomulco de Zúñiga'),
  ('MX', 'Reynosa', 'Reynosa'),
  ('MX', 'Torreon', 'Torreón'),
  ('MX', 'Guadalupe', 'Guadalupe'),
  ('MX', 'Acapulco de Juarez', 'Acapulco de Juárez'),
  ('MX', 'Tlaquepaque', 'Tlaquepaque'),
  ('MX', 'Mazatlan', 'Mazatlán'),
  ('BR', 'Sao Paulo', 'São Paulo'),
  ('BR', 'Rio de Janeiro', 'Rio de Janeiro'),
  ('BR', 'Belo Horizonte', 'Belo Horizonte'),
  ('BR', 'Brasilia', 'Brasília'),
  ('BR', 'Salvador', 'Salvador'),
  ('BR', 'Fortaleza', 'Fortaleza'),
  ('BR', 'Manaus', 'Manaus'),
  ('BR', 'Santos', 'Santos'),
  ('BR', 'Curitiba', 'Curitiba'),
  ('BR', 'Recife', 'Recife'),
  ('BR', 'Belem', 'Belém'),
  ('BR', 'Porto Alegre', 'Porto Alegre'),
  ('BR', 'Goiania', 'Goiânia'),
  ('BR', 'Guarulhos', 'Guarulhos'),
  ('BR', 'Campinas', 'Campinas'),
  ('BR', 'Vila Velha', 'Vila Velha'),
  ('BR', 'Sao Luis', 'São Luís'),
  ('BR', 'Sao Goncalo', 'São Gonçalo'),
  ('BR', 'Maceio', 'Maceió'),
  ('BR', 'Natal', 'Natal'),
  ('BR', 'Teresina', 'Teresina'),
  ('BR', 'Campo Grande', 'Campo Grande'),
  ('BR', 'Iguacu', 'Iguaçu'),
  ('BR', 'Sao Bernardo do Campo', 'São Bernardo do Campo'),
  ('BR', 'Joao Pessoa', 'João Pessoa'),
  ('BR', 'Abaete', 'Abaeté'),
  ('BR', 'Sao Jose dos Campos', 'São José dos Campos'),
  ('BR', 'Santo Andre', 'Santo André'),
  ('BR', 'Ribeirao Preto', 'Ribeirão Prêto'),
  ('BR', 'Jaboatao', 'Jaboatão'),
  ('AR', 'Buenos Aires', 'Buenos Aires'),
  ('AR', 'Cordoba', 'Córdoba'),
  ('AR', 'Rosario', 'Rosario'),
  ('AR', 'Santiago del Estero', 'Santiago del Estero'),
  ('AR', 'Comodoro Rivadavia', 'Comodoro Rivadavia'),
  ('AR', 'Mar del Plata', 'Mar del Plata'),
  ('AR', 'San Miguel de Tucuman', 'San Miguel de Tucumán'),
  ('AR', 'Salta', 'Salta'),
  ('AR', 'San Juan', 'San Juan'),
  ('AR', 'Lanus', 'Lanús'),
  ('AR', 'Florencio Varela', 'Florencio Varela'),
  ('AR', 'Santa Fe', 'Santa Fe'),
  ('AR', 'Corrientes', 'Corrientes'),
  ('AR', 'San Salvador de Jujuy', 'San Salvador de Jujuy'),
  ('AR', 'Bahia Blanca', 'Bahía Blanca'),
  ('AR', 'Resistencia', 'Resistencia'),
  ('AR', 'Posadas', 'Posadas'),
  ('AR', 'Quilmes', 'Quilmes'),
  ('AR', 'Parana', 'Paraná'),
  ('AR', 'Merlo', 'Merlo'),
  ('CL', 'Santiago', 'Santiago'),
  ('CL', 'Concepcion', 'Concepción'),
  ('CL', 'Puente Alto', 'Puente Alto'),
  ('CL', 'Maipu', 'Maipú'),
  ('CL', 'La Florida', 'La Florida'),
  ('CL', 'Antofagasta', 'Antofagasta'),
  ('CL', 'Vina del Mar', 'Viña del Mar'),
  ('CL', 'San Bernardo', 'San Bernardo'),
  ('CL', 'Valparaiso', 'Valparaíso'),
  ('CL', 'Temuco', 'Temuco'),
  ('CL', 'Las Condes', 'Las Condes'),
  ('CL', 'Rancagua', 'Rancagua'),
  ('CL', 'Penalolen', 'Peñalolén'),
  ('CL', 'Quilicura', 'Quilicura'),
  ('CL', 'Talca', 'Talca'),
  ('CL', 'Coquimbo', 'Coquimbo'),
  ('CL', 'Arica', 'Arica'),
  ('CL', 'La Serena', 'La Serena'),
  ('CL', 'Iquique', 'Iquique'),
  ('CL', 'La Pintana', 'La Pintana'),
  ('CO', 'Bogota', 'Bogotá'),
  ('CO', 'Timbio', 'Timbío'),
  ('CO', 'Medellin', 'Medellín'),
  ('CO', 'Cali', 'Cali'),
  ('CO', 'Barranquilla', 'Barranquilla'),
  ('CO', 'Cartagena', 'Cartagena'),
  ('CO', 'Bucaramanga', 'Bucaramanga'),
  ('CO', 'Palermo', 'Palermo'),
  ('CO', 'Cucuta', 'Cúcuta'),
  ('CO', 'Soledad', 'Soledad'),
  ('CO', 'Villavicencio', 'Villavicencio'),
  ('CO', 'Pereira', 'Pereira'),
  ('CO', 'Valledupar', 'Valledupar'),
  ('CO', 'Ibague', 'Ibagué'),
  ('CO', 'Soacha', 'Soacha'),
  ('CO', 'Santa Marta', 'Santa Marta'),
  ('CO', 'Monteria', 'Montería'),
  ('CO', 'Bello', 'Bello'),
  ('CO', 'Manizales', 'Manizales'),
  ('CO', 'Buenaventura', 'Buenaventura'),
  ('CN', 'Guangzhou', 'Guangzhou'),
  ('CN', 'Shanghai', 'Shanghai'),
  ('CN', 'Beijing', 'Beijing'),
  ('CN', 'Shenzhen', 'Shenzhen'),
  ('CN', 'Chengdu', 'Chengdu'),
  ('CN', 'Xi''an', 'Xi’an'),
  ('CN', 'Chongqing', 'Chongqing'),
  ('CN', 'Baoding', 'Baoding'),
  ('CN', 'Linyi', 'Linyi'),
  ('CN', 'Dongguan', 'Dongguan'),
  ('CN', 'Tianjin', 'Tianjin'),
  ('CN', 'Wuhan', 'Wuhan'),
  ('CN', 'Nanyang', 'Nanyang'),
  ('CN', 'Hangzhou', 'Hangzhou'),
  ('CN', 'Foshan', 'Foshan'),
  ('CN', 'Tongshan', 'Tongshan'),
  ('CN', 'Zhoukou', 'Zhoukou'),
  ('CN', 'Ganzhou', 'Ganzhou'),
  ('CN', 'Heze', 'Heze'),
  ('CN', 'Quanzhou', 'Quanzhou'),
  ('CN', 'Nanjing', 'Nanjing'),
  ('CN', 'Jining', 'Jining'),
  ('CN', 'Fuyang', 'Fuyang'),
  ('CN', 'Shenyang', 'Shenyang'),
  ('CN', 'Shangqiu', 'Shangqiu'),
  ('CN', 'Cangzhou', 'Cangzhou'),
  ('CN', 'Shaoyang', 'Shaoyang'),
  ('CN', 'Zhanjiang', 'Zhanjiang'),
  ('CN', 'Yancheng', 'Yancheng'),
  ('CN', 'Hengyang', 'Hengyang'),
  ('JP', 'Tokyo', 'Tokyo'),
  ('JP', 'Osaka', 'Ōsaka'),
  ('JP', 'Nagoya', 'Nagoya'),
  ('JP', 'Yokohama', 'Yokohama'),
  ('JP', 'Fukuoka', 'Fukuoka'),
  ('JP', 'Sapporo', 'Sapporo'),
  ('JP', 'Kawasaki', 'Kawasaki'),
  ('JP', 'Kobe', 'Kōbe'),
  ('JP', 'Kyoto', 'Kyōto'),
  ('JP', 'Saitama', 'Saitama'),
  ('JP', 'Hiroshima', 'Hiroshima'),
  ('JP', 'Sendai', 'Sendai'),
  ('JP', 'Chiba', 'Chiba'),
  ('JP', 'Setagaya', 'Setagaya'),
  ('JP', 'Kitakyushu', 'Kitakyūshū'),
  ('JP', 'Sakai', 'Sakai'),
  ('JP', 'Niigata', 'Niigata'),
  ('JP', 'Hamamatsu', 'Hamamatsu'),
  ('JP', 'Nerima', 'Nerima'),
  ('JP', 'Kumamoto', 'Kumamoto'),
  ('JP', 'Ota-ku', 'Ōta-ku'),
  ('JP', 'Sagamihara', 'Sagamihara'),
  ('JP', 'Okayama', 'Okayama'),
  ('JP', 'Edogawa', 'Edogawa'),
  ('JP', 'Shizuoka', 'Shizuoka'),
  ('JP', 'Adachi', 'Adachi'),
  ('JP', 'Honcho', 'Honchō'),
  ('JP', 'Kagoshima', 'Kagoshima'),
  ('JP', 'Kawaguchi', 'Kawaguchi'),
  ('JP', 'Suginami-ku', 'Suginami-ku'),
  ('KR', 'Seoul', 'Seoul'),
  ('KR', 'Busan', 'Busan'),
  ('KR', 'Incheon', 'Incheon'),
  ('KR', 'Daegu', 'Daegu'),
  ('KR', 'Gwangju', 'Gwangju'),
  ('KR', 'Daejeon', 'Daejeon'),
  ('KR', 'Suwon', 'Suwon'),
  ('KR', 'Ulsan', 'Ulsan'),
  ('KR', 'Tongjin', 'Tongjin'),
  ('KR', 'Goyang', 'Goyang'),
  ('KR', 'Changwon', 'Changwon'),
  ('KR', 'Songnam', 'Sŏngnam'),
  ('KR', 'Bucheon', 'Bucheon'),
  ('KR', 'Cheongju', 'Cheongju'),
  ('KR', 'Yanggok', 'Yanggok'),
  ('KR', 'Hwasu-dong', 'Hwasu-dong'),
  ('KR', 'Ansan', 'Ansan'),
  ('KR', 'Ch''onan', 'Ch’ŏnan'),
  ('KR', 'Jeonju', 'Jeonju'),
  ('KR', 'Anyang', 'Anyang'),
  ('IN', 'Delhi', 'دلهي'),
  ('IN', 'Mumbai', 'مومباي'),
  ('IN', 'Bangalore', 'بنغالور'),
  ('IN', 'Chennai', 'تشيناي'),
  ('IN', 'Kolkata', 'Kolkāta'),
  ('IN', 'Hyderabad', 'Hyderābād'),
  ('IN', 'Pune', 'Pune'),
  ('IN', 'Ahmedabad', 'Ahmedabad'),
  ('IN', 'Surat', 'Sūrat'),
  ('IN', 'Prayagraj', 'Prayagraj'),
  ('IN', 'Lucknow', 'Lucknow'),
  ('IN', 'Jaipur', 'Jaipur'),
  ('IN', 'Cawnpore', 'Cawnpore'),
  ('IN', 'Mirzapur', 'Mirzāpur'),
  ('IN', 'Nagpur', 'Nāgpur'),
  ('IN', 'Ghaziabad', 'Ghāziābād'),
  ('IN', 'Vadodara', 'Vadodara'),
  ('IN', 'Vishakhapatnam', 'Vishākhapatnam'),
  ('IN', 'Indore', 'Indore'),
  ('IN', 'Thane', 'Thāne'),
  ('IN', 'Bhopal', 'Bhopāl'),
  ('IN', 'Chinchvad', 'Chinchvad'),
  ('IN', 'Patna', 'Patna'),
  ('IN', 'Bilaspur', 'Bilāspur'),
  ('IN', 'Ludhiana', 'Ludhiāna'),
  ('IN', 'Agwar', 'Agwār'),
  ('IN', 'Agra', 'Āgra'),
  ('IN', 'Madurai', 'Madurai'),
  ('IN', 'Jamshedpur', 'Jamshedpur'),
  ('IN', 'Nasik', 'Nāsik'),
  ('PK', 'Karachi', 'كراتشي'),
  ('PK', 'Lahore', 'لاهور'),
  ('PK', 'Islamabad', 'إسلام آباد'),
  ('PK', 'Faisalabad', 'Faisalabad'),
  ('PK', 'Rawalpindi', 'Rawalpindi'),
  ('PK', 'Gujranwala', 'Gujranwala'),
  ('PK', 'Peshawar', 'Peshawar'),
  ('PK', 'Multan', 'Multan'),
  ('PK', 'Saidu Sharif', 'Saidu Sharif'),
  ('PK', 'Hyderabad City', 'Hyderabad City'),
  ('PK', 'Quetta', 'Quetta'),
  ('PK', 'Bahawalpur', 'Bahawalpur'),
  ('PK', 'Sargodha', 'Sargodha'),
  ('PK', 'Sialkot City', 'Sialkot City'),
  ('PK', 'Sukkur', 'Sukkur'),
  ('PK', 'Larkana', 'Larkana'),
  ('PK', 'Chiniot', 'Chiniot'),
  ('PK', 'Shekhupura', 'Shekhupura'),
  ('PK', 'Rahimyar Khan', 'Rahimyar Khan'),
  ('PK', 'Jhang City', 'Jhang City'),
  ('PK', 'Dera Ghazi Khan', 'Dera Ghazi Khan'),
  ('PK', 'Gujrat', 'Gujrat'),
  ('PK', 'Cantonment', 'Cantonment'),
  ('PK', 'Bhawana', 'Bhawana'),
  ('PK', 'Mardan', 'Mardan'),
  ('PK', 'Sarai Alamgir', 'Sarai Alamgir'),
  ('PK', 'Shah Latif Town', 'Shah Latif Town'),
  ('PK', 'Kasur', 'Kasur'),
  ('PK', 'Chakwal', 'Chakwal'),
  ('PK', 'Mingaora', 'Mingaora'),
  ('BD', 'Dhaka', 'Dhaka'),
  ('BD', 'Chattogram', 'Chattogram'),
  ('BD', 'Narayanganj', 'Nārāyanganj'),
  ('BD', 'Khulna', 'Khulna'),
  ('BD', 'Gazipura', 'Gāzipura'),
  ('BD', 'Rangapukur', 'Rangapukur'),
  ('BD', 'Rajshahi', 'Rājshāhi'),
  ('BD', 'Mymensingh', 'Mymensingh'),
  ('BD', 'Faridpur', 'Farīdpur'),
  ('BD', 'Sylhet', 'Sylhet'),
  ('BD', 'Barura', 'Barura'),
  ('BD', 'Chauddagram', 'Chauddagram'),
  ('BD', 'Kushtia', 'Kushtia'),
  ('BD', 'Bogra', 'Bogra'),
  ('BD', 'Tangail', 'Tāngāil'),
  ('BD', 'Tungi', 'Tungi'),
  ('BD', 'Comilla', 'Comilla'),
  ('BD', 'Rangpur', 'Rangpur'),
  ('BD', 'Companiganj', 'Companiganj'),
  ('BD', 'Dinajpur', 'Dinājpur'),
  ('ID', 'Jakarta', 'Jakarta'),
  ('ID', 'Surabaya', 'Surabaya'),
  ('ID', 'Medan', 'Medan'),
  ('ID', 'Malang', 'Malang'),
  ('ID', 'Bekasi', 'Bekasi'),
  ('ID', 'Depok', 'Depok'),
  ('ID', 'Tangerang', 'Tangerang'),
  ('ID', 'Denpasar', 'Denpasar'),
  ('ID', 'Sangereng', 'Sangereng'),
  ('ID', 'Semarang', 'Semarang'),
  ('ID', 'Palembang', 'Palembang'),
  ('ID', 'Makassar', 'Makassar'),
  ('ID', 'Jepara', 'Jepara'),
  ('ID', 'Sumedang', 'Sumedang'),
  ('ID', 'Bagam', 'Bagam'),
  ('ID', 'Cilacap', 'Cilacap'),
  ('ID', 'Bandar Lampung', 'Bandar Lampung'),
  ('ID', 'Bogor', 'Bogor'),
  ('ID', 'Pekanbaru', 'Pekanbaru'),
  ('ID', 'Padang', 'Padang'),
  ('ID', 'Samarinda', 'Samarinda'),
  ('ID', 'Banjarmasin', 'Banjarmasin'),
  ('ID', 'Tasikmalaya', 'Tasikmalaya'),
  ('ID', 'Pontianak', 'Pontianak'),
  ('ID', 'Serang', 'Serang'),
  ('ID', 'Jambi', 'Jambi'),
  ('ID', 'Balikpapan', 'Balikpapan'),
  ('ID', 'Cimahi', 'Cimahi'),
  ('ID', 'Surakarta', 'Surakarta'),
  ('ID', 'Lembok', 'Lembok'),
  ('MY', 'Kuala Lumpur', 'Kuala Lumpur'),
  ('MY', 'Seberang Jaya', 'Seberang Jaya'),
  ('MY', 'Klang', 'Klang'),
  ('MY', 'Ipoh', 'Ipoh'),
  ('MY', 'Butterworth', 'Butterworth'),
  ('MY', 'George Town', 'George Town'),
  ('MY', 'Petaling Jaya', 'Petaling Jaya'),
  ('MY', 'Kuantan', 'Kuantan'),
  ('MY', 'Shah Alam', 'Shah Alam'),
  ('MY', 'Johor Bahru', 'Johor Bahru'),
  ('MY', 'Kota Bharu', 'Kota Bharu'),
  ('MY', 'Melaka', 'Melaka'),
  ('MY', 'Kota Kinabalu', 'Kota Kinabalu'),
  ('MY', 'Seremban', 'Seremban'),
  ('MY', 'Sandakan', 'Sandakan'),
  ('MY', 'Sungai Petani', 'Sungai Petani'),
  ('MY', 'Kuching', 'Kuching'),
  ('MY', 'Pasir Gudang', 'Pasir Gudang'),
  ('MY', 'Kuala Terengganu', 'Kuala Terengganu'),
  ('MY', 'Sibu', 'Sibu'),
  ('SG', 'Singapore', 'Singapore'),
  ('TH', 'Bangkok', 'Bangkok'),
  ('TH', 'Chiang Mai', 'Chiang Mai'),
  ('TH', 'Nonthaburi', 'Nonthaburi'),
  ('TH', 'Pak Kret', 'Pak Kret'),
  ('TH', 'Hat Yai', 'Hat Yai'),
  ('TH', 'Nakhon Ratchasima', 'Nakhon Ratchasima'),
  ('TH', 'Surat Thani', 'Surat Thani'),
  ('TH', 'Udon Thani', 'Udon Thani'),
  ('TH', 'Ban Bang Pu Mai', 'Ban Bang Pu Mai'),
  ('TH', 'Khon Kaen', 'Khon Kaen'),
  ('TH', 'Phatthaya', 'Phatthaya'),
  ('TH', 'Nakhon Si Thammarat', 'Nakhon Si Thammarat'),
  ('TH', 'Ban Mangkon', 'Ban Mangkon'),
  ('TH', 'Ban Laem Chabang', 'Ban Laem Chabang'),
  ('TH', 'Nakhon Sawan', 'Nakhon Sawan'),
  ('TH', 'Ban Talat Rangsit', 'Ban Talat Rangsit'),
  ('TH', 'Ubon Ratchathani', 'Ubon Ratchathani'),
  ('TH', 'Nakhon Pathom', 'Nakhon Pathom'),
  ('TH', 'Phuket', 'Phuket'),
  ('TH', 'Ban Tha Khlong', 'Ban Tha Khlong'),
  ('PH', 'Manila', 'Manila'),
  ('PH', 'Quezon City', 'Quezon City'),
  ('PH', 'Davao', 'Davao'),
  ('PH', 'Caloocan City', 'Caloocan City'),
  ('PH', 'Canagatan', 'Canagatan'),
  ('PH', 'Zamboanga City', 'Zamboanga City'),
  ('PH', 'Cebu City', 'Cebu City'),
  ('PH', 'Antipolo', 'Antipolo'),
  ('PH', 'Taguig City', 'Taguig City'),
  ('PH', 'Pasig City', 'Pasig City'),
  ('PH', 'Cagayan de Oro', 'Cagayan de Oro'),
  ('PH', 'Valenzuela', 'Valenzuela'),
  ('PH', 'Dasmarinas', 'Dasmariñas'),
  ('PH', 'General Santos', 'General Santos'),
  ('PH', 'City of Paranaque', 'City of Parañaque'),
  ('PH', 'Bacoor', 'Bacoor'),
  ('PH', 'Tondo', 'Tondo'),
  ('PH', 'San Jose del Monte', 'San Jose del Monte'),
  ('PH', 'Makati City', 'Makati City'),
  ('PH', 'Las Pinas City', 'Las Piñas City'),
  ('VN', 'Ho Chi Minh City', 'Ho Chi Minh City'),
  ('VN', 'Hanoi', 'Hanoi'),
  ('VN', 'Haiphong', 'Haiphong'),
  ('VN', 'Can Tho', 'Cần Thơ'),
  ('VN', 'Bien Hoa', 'Biên Hòa'),
  ('VN', 'Thu Duc', 'Thủ Đức'),
  ('VN', 'Quang Ha', 'Quảng Hà'),
  ('VN', 'Hue', 'Huế'),
  ('VN', 'Tan An', 'Tân An'),
  ('VN', 'Bac Ninh', 'Bắc Ninh'),
  ('VN', 'Hai Duong', 'Hải Dương'),
  ('VN', 'Vinh', 'Vinh'),
  ('VN', 'Tan Uyen', 'Tân Uyên'),
  ('VN', 'Thu Dau Mot', 'Thủ Dầu Một'),
  ('VN', 'Thanh Hoa', 'Thanh Hóa'),
  ('VN', 'Nha Trang', 'Nha Trang'),
  ('VN', 'Nam Dinh', 'Nam Định'),
  ('VN', 'Vung Tau', 'Vũng Tàu'),
  ('VN', 'Buon Ma Thuot', 'Buôn Ma Thuột'),
  ('VN', 'Thai Nguyen', 'Thái Nguyên'),
  ('AU', 'Sydney', 'Sydney'),
  ('AU', 'Melbourne', 'Melbourne'),
  ('AU', 'Brisbane', 'Brisbane'),
  ('AU', 'Perth', 'Perth'),
  ('AU', 'Adelaide', 'Adelaide'),
  ('AU', 'Gold Coast', 'Gold Coast'),
  ('AU', 'Cranbourne', 'Cranbourne'),
  ('AU', 'Canberra', 'Canberra'),
  ('AU', 'Central Coast', 'Central Coast'),
  ('AU', 'Wollongong', 'Wollongong'),
  ('AU', 'Hobart', 'Hobart'),
  ('AU', 'Geelong', 'Geelong'),
  ('AU', 'Townsville', 'Townsville'),
  ('AU', 'Ipswich', 'Ipswich'),
  ('AU', 'Newcastle', 'Newcastle'),
  ('AU', 'Cairns', 'Cairns'),
  ('AU', 'Darwin', 'Darwin'),
  ('AU', 'Toowoomba', 'Toowoomba'),
  ('AU', 'Launceston', 'Launceston'),
  ('AU', 'Ballarat', 'Ballarat'),
  ('NZ', 'Auckland', 'Auckland'),
  ('NZ', 'Wellington', 'Wellington'),
  ('NZ', 'Christchurch', 'Christchurch'),
  ('NZ', 'Manukau City', 'Manukau City'),
  ('NZ', 'Waitakere', 'Waitakere'),
  ('NZ', 'Northcote', 'Northcote'),
  ('NZ', 'Hamilton', 'Hamilton'),
  ('NZ', 'Tauranga', 'Tauranga'),
  ('NZ', 'Lower Hutt', 'Lower Hutt'),
  ('NZ', 'Dunedin', 'Dunedin'),
  ('NZ', 'Palmerston North', 'Palmerston North'),
  ('NZ', 'Napier', 'Napier'),
  ('NZ', 'Porirua', 'Porirua'),
  ('NZ', 'Rotorua', 'Rotorua'),
  ('NZ', 'New Plymouth', 'New Plymouth'),
  ('NZ', 'Whangarei', 'Whangarei'),
  ('NZ', 'Invercargill', 'Invercargill'),
  ('NZ', 'Nelson', 'Nelson'),
  ('NZ', 'Upper Hutt', 'Upper Hutt'),
  ('NZ', 'Whanganui', 'Whanganui'),
  ('ZA', 'Johannesburg', 'Johannesburg'),
  ('ZA', 'Soweto', 'Soweto'),
  ('ZA', 'Vereeniging', 'Vereeniging'),
  ('ZA', 'Pietermaritzburg', 'Pietermaritzburg'),
  ('ZA', 'Pretoria', 'Pretoria'),
  ('ZA', 'Durban', 'Durban'),
  ('ZA', 'Rustenburg', 'Rustenburg'),
  ('ZA', 'Kimberley', 'Kimberley'),
  ('ZA', 'Katlehong', 'Katlehong'),
  ('ZA', 'Cape Town', 'Cape Town'),
  ('ZA', 'Welkom', 'Welkom'),
  ('ZA', 'Khayelitsha', 'Khayelitsha'),
  ('ZA', 'Newcastle', 'Newcastle'),
  ('ZA', 'East London', 'East London'),
  ('ZA', 'Randburg', 'Randburg'),
  ('ZA', 'Roodepoort', 'Roodepoort'),
  ('ZA', 'Port Elizabeth', 'Port Elizabeth'),
  ('ZA', 'Mitchells Plain', 'Mitchells Plain'),
  ('ZA', 'Boksburg', 'Boksburg'),
  ('ZA', 'Bloemfontein', 'Bloemfontein'),
  ('NG', 'Lagos', 'Lagos'),
  ('NG', 'Kano', 'Kano'),
  ('NG', 'Abuja', 'Abuja'),
  ('NG', 'Ibadan', 'Ibadan'),
  ('NG', 'Port Harcourt', 'Port Harcourt'),
  ('NG', 'Aba', 'Aba'),
  ('NG', 'Onitsha', 'Onitsha'),
  ('NG', 'Maiduguri', 'Maiduguri'),
  ('NG', 'Benin City', 'Benin City'),
  ('NG', 'Shagamu', 'Shagamu'),
  ('NG', 'Ikare', 'Ikare'),
  ('NG', 'Ogbomoso', 'Ogbomoso'),
  ('NG', 'Owerri', 'Owerri'),
  ('NG', 'Abeokuta', 'Abeokuta'),
  ('NG', 'Ikeja', 'Ikeja'),
  ('NG', 'Akure', 'Akure'),
  ('NG', 'Ilorin', 'Ilorin'),
  ('NG', 'Warri', 'Warri'),
  ('NG', 'Kaduna', 'Kaduna'),
  ('NG', 'Osogbo', 'Osogbo'),
  ('NG', 'Enugu', 'Enugu'),
  ('NG', 'Bauchi', 'Bauchi'),
  ('NG', 'Jalingo', 'Jalingo'),
  ('NG', 'Jos', 'Jos'),
  ('NG', 'Ile-Ife', 'Ile-Ife'),
  ('NG', 'Calabar', 'Calabar'),
  ('NG', 'Agege', 'Agege'),
  ('NG', 'Ado-Ekiti', 'Ado-Ekiti'),
  ('NG', 'Uyo', 'Uyo'),
  ('NG', 'Sokoto', 'Sokoto'),
  ('KE', 'Nairobi', 'Nairobi'),
  ('KE', 'Meru', 'Meru'),
  ('KE', 'Mombasa', 'Mombasa'),
  ('KE', 'Kisumu', 'Kisumu'),
  ('KE', 'Kikuyu', 'Kikuyu'),
  ('KE', 'Nakuru', 'Nakuru'),
  ('KE', 'Eldoret', 'Eldoret'),
  ('KE', 'Habaswein', 'Habaswein'),
  ('KE', 'Ongata Rongai', 'Ongata Rongai'),
  ('KE', 'Molo', 'Molo'),
  ('KE', 'Kitenkela', 'Kitenkela'),
  ('KE', 'Kiambu', 'Kiambu'),
  ('KE', 'Ramu', 'Ramu'),
  ('KE', 'Kilifi', 'Kilifi'),
  ('KE', 'Malindi', 'Malindi'),
  ('KE', 'Vihiga', 'Vihiga'),
  ('KE', 'Machakos', 'Machakos'),
  ('KE', 'Ngong', 'Ngong'),
  ('KE', 'Mumias', 'Mumias'),
  ('KE', 'Thika', 'Thika'),
  ('ET', 'Addis Ababa', 'Addis Ababa'),
  ('ET', 'Gode', 'Godē'),
  ('ET', 'Erer Sata', 'Ērer Sātā'),
  ('ET', 'Nazret', 'Nazrēt'),
  ('ET', 'Gonder', 'Gonder'),
  ('ET', 'Mekele', 'Mekele'),
  ('ET', 'Awasa', 'Āwasa'),
  ('ET', 'Dire Dawa', 'Dire Dawa'),
  ('ET', 'Bahir Dar', 'Bahir Dar'),
  ('ET', 'Shashemene', 'Shashemenē'),
  ('ET', 'Sodo', 'Sodo'),
  ('ET', 'Arba Minch''', 'Ārba Minch’'),
  ('ET', 'Dese', 'Desē'),
  ('ET', 'Hosa''ina', 'Hosa’ina'),
  ('ET', 'Jima', 'Jīma'),
  ('ET', 'Harar', 'Harar'),
  ('ET', 'Jijiga', 'Jijiga'),
  ('ET', 'Dila', 'Dīla'),
  ('ET', 'Nek''emte', 'Nek’emtē'),
  ('ET', 'Debre Birhan', 'Debre Birhan'),
  ('GH', 'Boankra', 'Boankra'),
  ('GH', 'Accra', 'Accra'),
  ('GH', 'Kumasi', 'Kumasi'),
  ('GH', 'Tamale', 'Tamale'),
  ('GH', 'Domaa-Ahenkro', 'Domaa-Ahenkro'),
  ('GH', 'Sekondi', 'Sekondi'),
  ('GH', 'Sunyani', 'Sunyani'),
  ('GH', 'Ashaiman', 'Ashaiman'),
  ('GH', 'Obuase', 'Obuase'),
  ('GH', 'Cape Coast', 'Cape Coast'),
  ('GH', 'Tema', 'Tema'),
  ('GH', 'Medina Estates', 'Medina Estates'),
  ('GH', 'Koforidua', 'Koforidua'),
  ('GH', 'Suhum', 'Suhum'),
  ('GH', 'Kintampo', 'Kintampo'),
  ('GH', 'Wa', 'Wa'),
  ('GH', 'Atebubu', 'Atebubu'),
  ('GH', 'Techiman', 'Techiman'),
  ('GH', 'Dzolokpuita', 'Dzolokpuita'),
  ('GH', 'Ho', 'Ho'),
  ('SN', 'Dakar', 'Dakar'),
  ('SN', 'Pikine', 'Pikine'),
  ('SN', 'Touba', 'Touba'),
  ('SN', 'Thies', 'Thiès'),
  ('SN', 'Guediawaye', 'Guédiawaye'),
  ('SN', 'Dagana', 'Dagana'),
  ('SN', 'Rufisque', 'Rufisque'),
  ('SN', 'Ziguinchor', 'Ziguinchor'),
  ('SN', 'Saint-Louis', 'Saint-Louis'),
  ('SN', 'Kaolack', 'Kaolack'),
  ('SN', 'Diourbel', 'Diourbel'),
  ('SN', 'Richard-Toll', 'Richard-Toll'),
  ('SN', 'Louga', 'Louga'),
  ('SN', 'Tambacounda', 'Tambacounda'),
  ('SN', 'Mbake', 'Mbaké'),
  ('SN', 'Kolda', 'Kolda'),
  ('SN', 'Bargny', 'Bargny'),
  ('SN', 'Joal-Fadiout', 'Joal-Fadiout'),
  ('SN', 'Paoskoto', 'Paoskoto'),
  ('SN', 'Tivaouane', 'Tivaouane'),
  ('TN', 'Tunis', 'Tunis'),
  ('TN', 'Sidi Bouzid', 'Sidi Bouzid'),
  ('TN', 'Sfax', 'Sfax'),
  ('TN', 'Sousse', 'Sousse'),
  ('TN', 'Kairouan', 'Kairouan'),
  ('TN', 'Metouia', 'Métouia'),
  ('TN', 'Kebili', 'Kebili'),
  ('TN', 'Bizerte', 'Bizerte'),
  ('TN', 'Sukrah', 'Sukrah'),
  ('TN', 'Gabes', 'Gabès'),
  ('TN', 'Ariana', 'Ariana'),
  ('TN', 'Sakiet ed Daier', 'Sakiet ed Daier'),
  ('TN', 'Jendouba', 'Jendouba'),
  ('TN', 'Gafsa', 'Gafsa'),
  ('TN', 'Msaken', 'Msaken'),
  ('TN', 'Medenine', 'Medenine'),
  ('TN', 'Beja', 'Béja'),
  ('TN', 'Kasserine', 'Kasserine'),
  ('TN', 'Monastir', 'Monastir'),
  ('TN', 'Rades', 'Radès'),
  ('DZ', 'Algiers', 'Algiers'),
  ('DZ', 'Oran', 'Oran'),
  ('DZ', 'Constantine', 'Constantine'),
  ('DZ', 'Blida', 'Blida'),
  ('DZ', 'Batna', 'Batna'),
  ('DZ', 'Setif', 'Sétif'),
  ('DZ', 'Djelfa', 'Djelfa'),
  ('DZ', 'Annaba', 'Annaba'),
  ('DZ', 'Sidi Bel Abbes', 'Sidi Bel Abbès'),
  ('DZ', 'Biskra', 'Biskra'),
  ('DZ', 'Tebessa', 'Tébessa'),
  ('DZ', 'Tiaret', 'Tiaret'),
  ('DZ', 'Bejaia', 'Bejaïa'),
  ('DZ', 'Tlemcen', 'Tlemcen'),
  ('DZ', 'Bordj Bou Arreridj', 'Bordj Bou Arreridj'),
  ('DZ', 'Bechar', 'Béchar'),
  ('DZ', 'Skikda', 'Skikda'),
  ('DZ', 'Souk Ahras', 'Souk Ahras'),
  ('DZ', 'Chlef', 'Chlef'),
  ('DZ', 'El Eulma', 'El Eulma'),
  ('LY', 'Tripoli', 'Tripoli'),
  ('LY', 'Benghazi', 'Benghazi'),
  ('LY', 'Ajdabiya', 'Ajdābiyā'),
  ('LY', 'Misratah', 'Mişrātah'),
  ('LY', 'Al Bayda''', 'Al Bayḑā’'),
  ('LY', 'Al Khums', 'Al Khums'),
  ('LY', 'Az Zawiyah', 'Az Zāwīyah'),
  ('LY', 'Gharyan', 'Gharyān'),
  ('LY', 'Al Marj', 'Al Marj'),
  ('LY', 'Tobruk', 'Tobruk'),
  ('LY', 'Darnah', 'Darnah'),
  ('LY', 'Sabha', 'Sabhā'),
  ('LY', 'Sabratah', 'Şabrātah'),
  ('LY', 'Al Jumayl', 'Al Jumayl'),
  ('LY', 'Janzur', 'Janzūr'),
  ('LY', 'Zuwarah', 'Zuwārah'),
  ('LY', 'Masallatah', 'Masallātah'),
  ('LY', 'Surt', 'Surt'),
  ('LY', 'Yafran', 'Yafran'),
  ('LY', 'Nalut', 'Nālūt'),
  ('SD', 'Khartoum', 'Khartoum'),
  ('SD', 'Omdurman', 'Omdurman'),
  ('SD', 'Al Mijlad', 'Al Mijlad'),
  ('SD', 'Khartoum North', 'Khartoum North'),
  ('SD', 'Port Sudan', 'Port Sudan'),
  ('SD', 'Kassala', 'Kassala'),
  ('SD', 'Nyala', 'Nyala'),
  ('SD', 'El Obeid', 'El Obeid'),
  ('SD', 'Gedaref', 'Gedaref'),
  ('SD', 'Wad Medani', 'Wad Medani'),
  ('SD', 'Kusti', 'Kūstī'),
  ('SD', 'Ed Daein', 'Ed Daein'),
  ('SD', 'El Fasher', 'El Fasher'),
  ('SD', 'Singa', 'Singa'),
  ('SD', 'El Geneina', 'El Geneina'),
  ('SD', 'Kurmuk', 'Kurmuk'),
  ('SD', 'Ar Ruseris', 'Ar Ruseris'),
  ('SD', 'Shendi', 'Shendi'),
  ('SD', 'Ed Damazin', 'Ed Damazin'),
  ('SD', 'Kadugli', 'Kadugli'),
  ('LB', 'Tripoli', 'Tripoli'),
  ('LB', 'Beirut', 'Beirut'),
  ('LB', 'Sidon', 'Sidon'),
  ('LB', 'Tyre', 'Tyre'),
  ('LB', 'Borj Hammoud', 'Borj Hammoud'),
  ('LB', 'El Minie', 'El Minié'),
  ('LB', 'Aaley', 'Aaley'),
  ('LB', 'Jounie', 'Joünié'),
  ('LB', 'Zahle', 'Zahlé'),
  ('LB', 'Nabatiye', 'Nabatîyé'),
  ('LB', 'Borj el Qoble', 'Borj el Qoblé'),
  ('LB', 'El Ghaziye', 'El Ghâzîyé'),
  ('LB', 'Qabb Elias', 'Qabb Eliâs'),
  ('LB', 'Aarsal', 'Aarsâl'),
  ('LB', 'Batroun', 'Batroûn'),
  ('LB', 'Jbail', 'Jbaïl'),
  ('LB', 'Barr Elias', 'Barr Eliâs'),
  ('LB', 'Zgharta', 'Zghartā'),
  ('LB', 'Bent Jbail', 'Bent Jbaïl'),
  ('LB', 'Chmistar', 'Chmistâr'),
  ('SY', 'Aleppo', 'Aleppo'),
  ('SY', 'Damascus', 'Damascus'),
  ('SY', 'Homs', 'Homs'),
  ('SY', 'Latakia', 'Latakia'),
  ('SY', 'Hamah', 'Ḩamāh'),
  ('SY', 'Ar Raqqah', 'Ar Raqqah'),
  ('SY', 'Dayr az Zawr', 'Dayr az Zawr'),
  ('SY', 'Al Hasakah', 'Al Ḩasakah'),
  ('SY', 'Al Qamishli', 'Al Qāmishlī'),
  ('SY', 'Idlib', 'Idlib'),
  ('SY', 'Dar`a', 'Dar‘ā'),
  ('SY', 'Qabr as Sitt', 'Qabr as Sitt'),
  ('SY', 'Duma', 'Dūmā'),
  ('SY', 'Jaramana', 'Jaramānā'),
  ('SY', 'As Salamiyah', 'As Salamīyah'),
  ('SY', 'As Safirah', 'As Safīrah'),
  ('SY', 'Al Hajar al Aswad', 'Al Ḩajar al Aswad'),
  ('SY', 'Ma`arrat an Nu`man', 'Ma‘arrat an Nu‘mān'),
  ('SY', 'Tartus', 'Ţarţūs'),
  ('SY', 'Darayya', 'Dārayyā'),
  ('IQ', 'Baghdad', 'Baghdad'),
  ('IQ', 'Mosul', 'Mosul'),
  ('IQ', 'Al Basrah', 'Al Başrah'),
  ('IQ', 'Kirkuk', 'Kirkuk'),
  ('IQ', 'As Sulaymaniyah', 'As Sulaymānīyah'),
  ('IQ', 'Ar Ramadi', 'Ar Ramādī'),
  ('IQ', 'Erbil', 'Erbil'),
  ('IQ', 'An Najaf', 'An Najaf'),
  ('IQ', 'Karbala''', 'Karbalā’'),
  ('IQ', 'An Nasiriyah', 'An Nāşirīyah'),
  ('IQ', 'Al Hillah', 'Al Ḩillah'),
  ('IQ', 'Al `Amarah', 'Al ‘Amārah'),
  ('IQ', 'Ba`qubah', 'Ba‘qūbah'),
  ('IQ', 'Ad Diwaniyah', 'Ad Dīwānīyah'),
  ('IQ', 'Az Zubayr', 'Az Zubayr'),
  ('IQ', 'Dahuk', 'Dahūk'),
  ('IQ', 'Al Fallujah', 'Al Fallūjah'),
  ('IQ', 'Al Kut', 'Al Kūt'),
  ('IQ', 'Ash Shamiyah', 'Ash Shāmīyah'),
  ('IQ', 'Al Qurnah', 'Al Qurnah'),
  ('IR', 'Tehran', 'Tehran'),
  ('IR', 'Kashan', 'Kāshān'),
  ('IR', 'Mashhad', 'Mashhad'),
  ('IR', 'Esfahan', 'Eşfahān'),
  ('IR', 'Karaj', 'Karaj'),
  ('IR', 'Shiraz', 'Shīrāz'),
  ('IR', 'Tabriz', 'Tabrīz'),
  ('IR', 'Ahvaz', 'Ahvāz'),
  ('IR', 'Qom', 'Qom'),
  ('IR', 'Kermanshah', 'Kermānshāh'),
  ('IR', 'Kerman', 'Kermān'),
  ('IR', 'Orumiyeh', 'Orūmīyeh'),
  ('IR', 'Rasht', 'Rasht'),
  ('IR', 'Bahar', 'Bahār'),
  ('IR', 'Zahedan', 'Zāhedān'),
  ('IR', 'Hamadan', 'Hamadān'),
  ('IR', 'Yazd', 'Yazd'),
  ('IR', 'Ardabil', 'Ardabīl'),
  ('IR', 'Bandar `Abbas', 'Bandar ‘Abbās'),
  ('IR', 'Arak', 'Arāk'),
  ('YE', 'Sanaa', 'Sanaa'),
  ('YE', 'Ta`izz', 'Ta‘izz'),
  ('YE', 'Al Hudaydah', 'Al Ḩudaydah'),
  ('YE', 'Aden', 'Aden'),
  ('YE', 'Ibb', 'Ibb'),
  ('YE', 'Dhamar', 'Dhamār'),
  ('YE', 'Al Mukalla', 'Al Mukallā'),
  ('YE', 'Al Mansurah', 'Al Manşūrah'),
  ('YE', 'Tarim', 'Tarīm'),
  ('YE', 'Ash Shaykh `Uthman', 'Ash Shaykh ‘Uthmān'),
  ('YE', 'Zinjibar', 'Zinjibār'),
  ('YE', 'Sa`dah', 'Şa‘dah'),
  ('YE', 'Say''un', 'Say’ūn'),
  ('YE', 'Ash Shihr', 'Ash Shiḩr'),
  ('YE', 'At Tawahi', 'At Tawāhī'),
  ('YE', 'Zabid', 'Zabīd'),
  ('YE', 'Al Ma`alla''', 'Al Ma‘allā’'),
  ('YE', 'Hajjah', 'Ḩajjah'),
  ('YE', 'Bajil', 'Bājil'),
  ('YE', 'Rada`', 'Radā‘'),
  ('PS', 'Ramallah', 'رام الله'),
  ('PS', 'Gaza City', 'غزة'),
  ('PS', 'Hebron', 'الخليل'),
  ('PS', 'Nablus', 'نابلس'),
  ('PS', 'Bethlehem', 'بيت لحم'),
  ('PS', 'Jenin', 'جنين'),
  ('PS', 'Jericho', 'أريحا'),
  ('PS', 'Tulkarm', 'طولكرم'),
  ('PS', 'Qalqilya', 'قلقيلية'),
  ('PS', 'Khan Yunis', 'خان يونس'),
  ('AF', 'Kabul', 'Kabul'),
  ('AF', 'Kandahar', 'Kandahār'),
  ('AF', 'Herat', 'Herāt'),
  ('AF', 'Farah', 'Farāh'),
  ('AF', 'Mazar-e Sharif', 'Mazār-e Sharīf'),
  ('AF', 'Lashkar Gah', 'Lashkar Gāh'),
  ('AF', 'Kunduz', 'Kunduz'),
  ('AF', 'Taluqan', 'Tāluqān'),
  ('AF', 'Jalalabad', 'Jalālābād'),
  ('AF', 'Shibirghan', 'Shibirghān'),
  ('AF', 'Zaranj', 'Zaranj'),
  ('AF', 'Khost', 'Khōst'),
  ('AF', 'Maimanah', 'Maīmanah'),
  ('AF', 'Mehtar Lam', 'Mehtar Lām'),
  ('AF', 'Ghazni', 'Ghaznī'),
  ('AF', 'Paghman', 'Paghmān'),
  ('AF', 'Pul-e Khumri', 'Pul-e Khumrī'),
  ('AF', 'Bamyan', 'Bāmyān'),
  ('AF', 'Charikar', 'Chārīkār'),
  ('AF', 'Balkh', 'Balkh'),
  ('AZ', 'Baku', 'Baku'),
  ('AZ', 'Sumqayit', 'Sumqayıt'),
  ('AZ', 'Ganca', 'Gəncə'),
  ('AZ', 'Agcabadi', 'Ağcabədi'),
  ('AZ', 'Mingacevir', 'Mingəçevir'),
  ('AZ', 'Xirdalan', 'Xırdalan'),
  ('AZ', 'Naxcivan', 'Naxçıvan'),
  ('AZ', 'Qaracuxur', 'Qaraçuxur'),
  ('AZ', 'Hovsan', 'Hövsan'),
  ('AZ', 'Bakixanov', 'Bakıxanov'),
  ('AZ', 'Sirvan', 'Şirvan'),
  ('AZ', 'Saki', 'Şəki'),
  ('AZ', 'Yevlax', 'Yevlax'),
  ('AZ', 'Satrovka', 'Şatrovka'),
  ('AZ', 'M.A. Rasulzada', 'M.Ə. Rəsulzadə'),
  ('AZ', 'Lankaran', 'Lənkəran'),
  ('AZ', 'Xankandi', 'Xankəndi'),
  ('AZ', 'Bilacari', 'Biləcəri'),
  ('AZ', 'Mastaga', 'Maştağa'),
  ('AZ', 'Qazyan', 'Qəzyan'),
  ('KZ', 'Almaty', 'Almaty'),
  ('KZ', 'Nur-Sultan', 'Nur-Sultan'),
  ('KZ', 'Shymkent', 'Shymkent'),
  ('KZ', 'Qaraghandy', 'Qaraghandy'),
  ('KZ', 'Aqtobe', 'Aqtöbe'),
  ('KZ', 'Taraz', 'Taraz'),
  ('KZ', 'Pavlodar', 'Pavlodar'),
  ('KZ', 'Semey', 'Semey'),
  ('KZ', 'Oskemen', 'Öskemen'),
  ('KZ', 'Atyrau', 'Atyraū'),
  ('KZ', 'Qyzylorda', 'Qyzylorda'),
  ('KZ', 'Oral', 'Oral'),
  ('KZ', 'Qostanay', 'Qostanay'),
  ('KZ', 'Petropavl', 'Petropavl'),
  ('KZ', 'Temirtau', 'Temirtaū'),
  ('KZ', 'Aqtau', 'Aqtaū'),
  ('KZ', 'Kokshetau', 'Kökshetaū'),
  ('KZ', 'Turkistan', 'Türkistan'),
  ('KZ', 'Ekibastuz', 'Ekibastuz'),
  ('KZ', 'Zhangaozen', 'Zhangaözen'),
  ('UZ', 'Tashkent', 'Tashkent'),
  ('UZ', 'Namangan', 'Namangan'),
  ('UZ', 'Samarkand', 'Samarkand'),
  ('UZ', 'Andijon', 'Andijon'),
  ('UZ', 'Qo`qon', 'Qo‘qon'),
  ('UZ', 'Nukus', 'Nukus'),
  ('UZ', 'Farg`ona', 'Farg‘ona'),
  ('UZ', 'Bukhara', 'Bukhara'),
  ('UZ', 'Qarshi', 'Qarshi'),
  ('UZ', 'Denov', 'Denov'),
  ('UZ', 'Marg`ilon', 'Marg‘ilon'),
  ('UZ', 'Iskandar', 'Iskandar'),
  ('UZ', 'Jizzax', 'Jizzax'),
  ('UZ', 'Chirchiq', 'Chirchiq'),
  ('UZ', 'Urganch', 'Urganch'),
  ('UZ', 'Termiz', 'Termiz'),
  ('UZ', 'Navoiy', 'Navoiy'),
  ('UZ', 'Angren', 'Angren'),
  ('UZ', 'Olmaliq', 'Olmaliq'),
  ('UZ', 'Kogon Shahri', 'Kogon Shahri'),
  ('IL', 'Tel Aviv-Yafo', 'Tel Aviv-Yafo'),
  ('IL', 'Jerusalem', 'Jerusalem'),
  ('IL', 'Haifa', 'Haifa'),
  ('IL', 'Rishon LeZiyyon', 'Rishon LeẔiyyon'),
  ('IL', 'Petah Tiqwa', 'Petaẖ Tiqwa'),
  ('IL', 'Ashdod', 'Ashdod'),
  ('IL', 'Netanya', 'Netanya'),
  ('IL', 'Beersheba', 'Beersheba'),
  ('IL', 'Holon', 'Holon'),
  ('IL', 'Bene Beraq', 'Bené Beraq'),
  ('IL', 'Ramat Gan', 'Ramat Gan'),
  ('IL', 'Ashqelon', 'Ashqelon'),
  ('IL', 'Rehovot', 'Reẖovot'),
  ('IL', 'Bat Yam', 'Bat Yam'),
  ('IL', 'Bet Shemesh', 'Bet Shemesh'),
  ('IL', 'Kefar Sava', 'Kefar Sava'),
  ('IL', 'Hadera', 'Hadera'),
  ('IL', 'Herzliyya', 'Herẕliyya'),
  ('IL', 'Modi`in Makkabbim Re`ut', 'Modi‘in Makkabbim Re‘ut'),
  ('IL', 'Nazareth', 'Nazareth'),
  ('CY', 'Nicosia', 'Nicosia'),
  ('CY', 'Limassol', 'Limassol'),
  ('CY', 'Larnaca', 'Larnaca'),
  ('CY', 'Paphos', 'Paphos'),
  ('CY', 'Famagusta', 'Famagusta'),
  ('CY', 'Kyrenia', 'Kyrenia'),
  ('CY', 'Kato Polemidia', 'Káto Polemídia'),
  ('CY', 'Aradippou', 'Aradíppou'),
  ('CY', 'Latsia', 'Latsia'),
  ('CY', 'Paralimni', 'Paralímni'),
  ('MT', 'Valletta', 'Valletta'),
  ('MT', 'Birkirkara', 'Birkirkara'),
  ('MT', 'Saint Paul''s Bay', 'Saint Paul’s Bay'),
  ('MT', 'Mosta', 'Mosta'),
  ('MT', 'Sliema', 'Sliema'),
  ('MT', 'Qormi', 'Qormi'),
  ('MT', 'Zabbar', 'Żabbar'),
  ('MT', 'Naxxar', 'Naxxar'),
  ('MT', 'San Gwann', 'San Ġwann'),
  ('MT', 'Marsaskala', 'Marsaskala'),
  ('RO', 'Bucharest', 'Bucharest'),
  ('RO', 'Cluj-Napoca', 'Cluj-Napoca'),
  ('RO', 'Timisoara', 'Timişoara'),
  ('RO', 'Brasov', 'Braşov'),
  ('RO', 'Iasi', 'Iaşi'),
  ('RO', 'Constanta', 'Constanţa'),
  ('RO', 'Craiova', 'Craiova'),
  ('RO', 'Galati', 'Galaţi'),
  ('RO', 'Ploiesti', 'Ploieşti'),
  ('RO', 'Oradea', 'Oradea'),
  ('RO', 'Braila', 'Brăila'),
  ('RO', 'Arad', 'Arad'),
  ('RO', 'Pitesti', 'Piteşti'),
  ('RO', 'Sibiu', 'Sibiu'),
  ('RO', 'Bacau', 'Bacău'),
  ('RO', 'Targu-Mures', 'Târgu-Mureş'),
  ('RO', 'Baia Mare', 'Baia Mare'),
  ('RO', 'Buzau', 'Buzău'),
  ('RO', 'Botosani', 'Botoşani'),
  ('RO', 'Satu Mare', 'Satu Mare'),
  ('CZ', 'Prague', 'Prague'),
  ('CZ', 'Olomouc', 'Olomouc'),
  ('CZ', 'Brno', 'Brno'),
  ('CZ', 'Ostrava', 'Ostrava'),
  ('CZ', 'Plzen', 'Plzeň'),
  ('CZ', 'Liberec', 'Liberec'),
  ('CZ', 'Ceske Budejovice', 'České Budějovice'),
  ('CZ', 'Hradec Kralove', 'Hradec Králové'),
  ('CZ', 'Usti nad Labem', 'Ústí nad Labem'),
  ('CZ', 'Pardubice', 'Pardubice'),
  ('CZ', 'Zlin', 'Zlín'),
  ('CZ', 'Havirov', 'Havířov'),
  ('CZ', 'Kladno', 'Kladno'),
  ('CZ', 'Most', 'Most'),
  ('CZ', 'Opava', 'Opava'),
  ('CZ', 'Frydek-Mistek', 'Frýdek-Místek'),
  ('CZ', 'Jihlava', 'Jihlava'),
  ('CZ', 'Karvina', 'Karviná'),
  ('CZ', 'Teplice', 'Teplice'),
  ('CZ', 'Chomutov', 'Chomutov'),
  ('HU', 'Budapest', 'Budapest'),
  ('HU', 'Debrecen', 'Debrecen'),
  ('HU', 'Szekesfehervar', 'Székesfehérvár'),
  ('HU', 'Gyor', 'Győr'),
  ('HU', 'Szeged', 'Szeged'),
  ('HU', 'Nyiregyhaza', 'Nyíregyháza'),
  ('HU', 'Kecskemet', 'Kecskemét'),
  ('HU', 'Miskolc', 'Miskolc'),
  ('HU', 'Szombathely', 'Szombathely'),
  ('HU', 'Pecs', 'Pécs'),
  ('HU', 'Veszprem', 'Veszprém'),
  ('HU', 'Kaposvar', 'Kaposvár'),
  ('HU', 'Sopron', 'Sopron'),
  ('HU', 'Erd', 'Érd'),
  ('HU', 'Szolnok', 'Szolnok'),
  ('HU', 'Tatabanya', 'Tatabánya'),
  ('HU', 'Bekescsaba', 'Békéscsaba'),
  ('HU', 'Zalaegerszeg', 'Zalaegerszeg'),
  ('HU', 'Eger', 'Eger'),
  ('HU', 'Nagykanizsa', 'Nagykanizsa')
) AS city(country_code, name_en, name_ar)
JOIN public.countries AS country ON country.code = city.country_code
ON CONFLICT (country_id, name_en) DO NOTHING;
