
INSERT INTO public.countries (code, name_en, name_ar, is_active) VALUES
  ('MA','Morocco','المغرب',true),
  ('GB','United Kingdom','المملكة المتحدة',true),
  ('US','United States','الولايات المتحدة',true),
  ('FR','France','فرنسا',true),
  ('DE','Germany','ألمانيا',true),
  ('IT','Italy','إيطاليا',true),
  ('ES','Spain','إسبانيا',true),
  ('NL','Netherlands','هولندا',true),
  ('BE','Belgium','بلجيكا',true),
  ('CH','Switzerland','سويسرا',true),
  ('SE','Sweden','السويد',true),
  ('NO','Norway','النرويج',true),
  ('DK','Denmark','الدنمارك',true),
  ('FI','Finland','فنلندا',true),
  ('IE','Ireland','أيرلندا',true),
  ('PT','Portugal','البرتغال',true),
  ('AT','Austria','النمسا',true),
  ('GR','اليونان','اليونان',true),
  ('PL','Poland','بولندا',true),
  ('RU','Russia','روسيا',true),
  ('UA','Ukraine','أوكرانيا',true),
  ('CA','Canada','كندا',true),
  ('MX','Mexico','المكسيك',true),
  ('BR','Brazil','البرازيل',true),
  ('AR','Argentina','الأرجنتين',true),
  ('CL','Chile','تشيلي',true),
  ('CO','Colombia','كولومبيا',true),
  ('CN','China','الصين',true),
  ('JP','Japan','اليابان',true),
  ('KR','South Korea','كوريا الجنوبية',true),
  ('IN','India','الهند',true),
  ('PK','Pakistan','باكستان',true),
  ('BD','Bangladesh','بنغلاديش',true),
  ('ID','Indonesia','إندونيسيا',true),
  ('MY','Malaysia','ماليزيا',true),
  ('SG','Singapore','سنغافورة',true),
  ('TH','Thailand','تايلاند',true),
  ('PH','Philippines','الفلبين',true),
  ('VN','Vietnam','فيتنام',true),
  ('AU','Australia','أستراليا',true),
  ('NZ','New Zealand','نيوزيلندا',true),
  ('ZA','South Africa','جنوب أفريقيا',true),
  ('NG','Nigeria','نيجيريا',true),
  ('KE','Kenya','كينيا',true),
  ('ET','Ethiopia','إثيوبيا',true),
  ('GH','Ghana','غانا',true),
  ('SN','Senegal','السنغال',true),
  ('TN','Tunisia','تونس',true),
  ('DZ','Algeria','الجزائر',true),
  ('LY','Libya','ليبيا',true),
  ('SD','Sudan','السودان',true),
  ('LB','Lebanon','لبنان',true),
  ('SY','Syria','سوريا',true),
  ('IQ','Iraq','العراق',true),
  ('IR','Iran','إيران',true),
  ('TR','Turkey','تركيا',true),
  ('YE','Yemen','اليمن',true),
  ('PS','Palestine','فلسطين',true),
  ('AF','Afghanistan','أفغانستان',true),
  ('AZ','Azerbaijan','أذربيجان',true),
  ('KZ','Kazakhstan','كازاخستان',true),
  ('UZ','Uzbekistan','أوزبكستان',true),
  ('IL','Israel','إسرائيل',true),
  ('CY','Cyprus','قبرص',true),
  ('MT','Malta','مالطا',true),
  ('RO','Romania','رومانيا',true),
  ('CZ','Czech Republic','جمهورية التشيك',true),
  ('HU','Hungary','المجر',true)
ON CONFLICT (code) DO NOTHING;

UPDATE public.countries SET name_en = 'Greece' WHERE code = 'GR';
